### ISSUE TITLE
[transfer] el-transfer搜索功能搜索逻辑问题

### ISSUE THREAD

**Issue by fanwww** [element-plus/element-plus#10727]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.22`
- Browser / OS: `Chrome/107.0.5304.107 (Windows NT 10.0; Win64; x64)`
- Build Tool: `Vite`

### Related Component

- `el-transfer`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdHJhbnNmZXJcbiAgICB2LW1vZGVsPVwidmFsdWVcIlxuICAgIGZpbHRlcmFibGVcbiAgICA6ZmlsdGVyLW1ldGhvZD1cImZpbHRlck1ldGhvZFwiXG4gICAgZmlsdGVyLXBsYWNlaG9sZGVyPVwiU3RhdGUgQWJicmV2aWF0aW9uc1wiXG4gICAgOmRhdGE9XCJkYXRhXCJcbiAgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmludGVyZmFjZSBPcHRpb24ge1xuICBrZXk6IG51bWJlclxuICBsYWJlbDogc3RyaW5nXG4gIGluaXRpYWw6IHN0cmluZ1xufVxuXG5jb25zdCBnZW5lcmF0ZURhdGEgPSAoKSA9PiB7XG4gIGNvbnN0IGRhdGE6IE9wdGlvbltdID0gW11cbiAgY29uc3Qgc3RhdGVzID0gW1xuICAgICdDYWxpZm9ybmlhJyxcbiAgICAnSWxsaW5vaXMnLFxuICAgICdNYXJ5bGFuZCcsXG4gICAgJ1RleGFzJyxcbiAgICAnRmxvcmlkYScsXG4gICAgJ0NvbG9yYWRvJyxcbiAgICAnQ29ubmVjdGljdXQgJyxcbiAgXVxuICBjb25zdCBpbml0aWFscyA9IFsnQ0EnLCAnSUwnLCAnTUQnLCAnVFgnLCAnRkwnLCAnQ08nLCAnQ1QnXVxuICBzdGF0ZXMuZm9yRWFjaCgoY2l0eSwgaW5kZXgpID0+IHtcbiAgICBkYXRhLnB1c2goe1xuICAgICAgbGFiZWw6IGNpdHksXG4gICAgICBrZXk6IGluZGV4LFxuICAgICAgaW5pdGlhbDogaW5pdGlhbHNbaW5kZXhdLFxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBkYXRhXG59XG5cbmNvbnN0IGRhdGEgPSByZWY8T3B0aW9uW10+KGdlbmVyYXRlRGF0YSgpKVxuY29uc3QgdmFsdWUgPSByZWYoW10pXG5cbmNvbnN0IGZpbHRlck1ldGhvZCA9IChxdWVyeSwgaXRlbSkgPT4ge1xuICByZXR1cm4gaXRlbS5pbml0aWFsLnRvTG93ZXJDYXNlKCkuaW5jbHVkZXMocXVlcnkudG9Mb3dlckNhc2UoKSlcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

搜索框输入c,筛选出'California','Colorado','Connecticut',输入o,只筛选出'Colorado'

### What is Expected?

输入o,筛选出'California','Illinois','Florida','Colorado','Connecticut'

### What is actually happening?

输入o,只筛选出'Colorado'

### Additional comments

不清楚原本就是要实现这种搜索效果,还是搜索逻辑出了问题,如果没问题,则关闭该issue,该组件本身也支持自定义搜索方法.

![OHO224_GW$0`34RR@GL8MB3](https://user-images.githubusercontent.com/98572444/203458502-e3bf9bed-bbe2-4b97-b394-d54399994ee3.png)
![J348$I$7L{@N ON{)32XU8P](https://user-images.githubusercontent.com/98572444/203458523-b065dc92-9712-408a-8d5d-ee5bfb4be911.png)
![1EVCX`E343T@Q96L_ E$)I6](https://user-images.githubusercontent.com/98572444/203458534-729ca9ce-71f2-43e5-8481-9ae5b390ceae.png)

**Comment by btea** [comment]
If you match by `label` instead of `initial`, you can meet your needs. [example](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdHJhbnNmZXJcbiAgICB2LW1vZGVsPVwidmFsdWVcIlxuICAgIGZpbHRlcmFibGVcbiAgICA6ZmlsdGVyLW1ldGhvZD1cImZpbHRlck1ldGhvZFwiXG4gICAgZmlsdGVyLXBsYWNlaG9sZGVyPVwiU3RhdGUgQWJicmV2aWF0aW9uc1wiXG4gICAgOmRhdGE9XCJkYXRhXCJcbiAgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmludGVyZmFjZSBPcHRpb24ge1xuICBrZXk6IG51bWJlclxuICBsYWJlbDogc3RyaW5nXG4gIGluaXRpYWw6IHN0cmluZ1xufVxuXG5jb25zdCBnZW5lcmF0ZURhdGEgPSAoKSA9PiB7XG4gIGNvbnN0IGRhdGE6IE9wdGlvbltdID0gW11cbiAgY29uc3Qgc3RhdGVzID0gW1xuICAgICdDYWxpZm9ybmlhJyxcbiAgICAnSWxsaW5vaXMnLFxuICAgICdNYXJ5bGFuZCcsXG4gICAgJ1RleGFzJyxcbiAgICAnRmxvcmlkYScsXG4gICAgJ0NvbG9yYWRvJyxcbiAgICAnQ29ubmVjdGljdXQgJyxcbiAgXVxuICBjb25zdCBpbml0aWFscyA9IFsnQ0EnLCAnSUwnLCAnTUQnLCAnVFgnLCAnRkwnLCAnQ08nLCAnQ1QnXVxuICBzdGF0ZXMuZm9yRWFjaCgoY2l0eSwgaW5kZXgpID0+IHtcbiAgICBkYXRhLnB1c2goe1xuICAgICAgbGFiZWw6IGNpdHksXG4gICAgICBrZXk6IGluZGV4LFxuICAgICAgaW5pdGlhbDogaW5pdGlhbHNbaW5kZXhdLFxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBkYXRhXG59XG5cbmNvbnN0IGRhdGEgPSByZWY8T3B0aW9uW10+KGdlbmVyYXRlRGF0YSgpKVxuY29uc3QgdmFsdWUgPSByZWYoW10pXG5cbmNvbnN0IGZpbHRlck1ldGhvZCA9IChxdWVyeSwgaXRlbSkgPT4ge1xuICByZXR1cm4gaXRlbS5sYWJlbC50b0xvd2VyQ2FzZSgpLmluY2x1ZGVzKHF1ZXJ5LnRvTG93ZXJDYXNlKCkpXG59XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)
