### ISSUE TITLE
[Feature Request] Provide the component state to the outside of the component

### ISSUE THREAD

**Issue by liaoliaojun** [element-plus/element-plus#1175]
### Existing Component
Yes

### Component Name
Pagination And All

### Description
I want to get the internal state of the direct component so that I don't have to declare external variables.

Advantage: This way, business state and logic are implemented in separate modules, and the Vue template is just the UI layer for display. Easy to change UI implementation at any time (Vue3/Composition API can work independently)

````
<template>
    <el-pagination
      layout="prev, pager, next"
      :key-value="pagerKey"
    />
</template>

<script>
import { usePagination } from '@element-plus/pagination/src/usePagination'
export default {
  data () {
    return {
      pagerKey: 'newPager',
    }
  },
  // Execute after initializing the props
  mounted () {
    const { currentPage, total, pageSize } = usePagination(this.pagerKey)
    currentPage.value = 2
    pageSize.value = 5
    total.value = 200
  },
}
</script>
````

See PR: https://github.com/element-plus/element-plus/pull/1174

**Comment by JeremyWuuuuu** [comment]
So the concept for `use` hooks, is that we do all the initialization in `setup`, using it inside the `mounted` lifecycle seems not to be a good idea. And I am not quite following the description of `throwing state outside`, you can just get the state of a component via `component ref`.

**Comment by liaoliaojun** [comment]
> So the concept for `use` hooks, is that we do all the initialization in `setup`, using it inside the `mounted` lifecycle seems not to be a good idea. And I am not quite following the description of `throwing state outside`, you can just get the state of a component via `component ref`.

Since the usehook comes after the props, I'm working on a solution (callback) to make sure the two are compatible with each other

**Comment by bastarder** [comment]
Why don't you use ref ?

**Comment by liaoliaojun** [comment]
> Why don't you use ref ?

The internal state of ref does not trigger an external responsive.

It's not work.
```
<template>
  <div>
    <el-pagination
      ref="pagination"
      :page-size="20"
      :total="1000"
      layout="prev, pager, next"
    />
  </div>
</template>

<script>
import { defineComponent, watchEffect, ref } from 'vue'

export default defineComponent({
  setup () {
    const pagination = ref()

    watchEffect(() => {
      if (pagination.value) {
        // no work
        console.log(pagination.value.currentPage)
      }
    })

    return {
      pagination,
    }
  },
})
</script>
```

**Comment by liaoliaojun** [comment]
> So the concept for `use` hooks, is that we do all the initialization in `setup`, using it inside the `mounted` lifecycle seems not to be a good idea. And I am not quite following the description of `throwing state outside`, you can just get the state of a component via `component ref`.

`component ref` not responsive state.   Refactor completed https://github.com/element-plus/element-plus/pull/1174.

**Comment by liaoliaojun** [comment]
Is there a conclusion to this idea? @JeremyWuuuuu

**Comment by Liiked** [comment]
I think you've made a fundamental misunderstanding the purpose of [composition API](https://v3.vuejs.org/guide/composition-api-introduction.html#why-composition-api). 

It says:
>  This alone can get our application pretty far in terms of maintainability and flexibility.

When we use `useXXX` means **some logic code** needs to be extracted for further reusable senario. Note that the concept of  **logic** , generally, it contains functionalities of what we create for,  which provides the integrated implementation of a function or component.

Says, a Pagination component already has a integrated implementation, then we use composition api to make it more flexible. In this case, component is divided to a more resuable way, which is **logic** and **view** . This implementation makes **logic impletation** can be used by any **Pagination-like view** which could be the start of  chaos and **let things drift**.

1.  Introducing a way to make things more flexible also makes communication between **logic** and **view** more complicated. User must put two or more separated functionalities together to merely run a component when it used to be easy. 
2.  It may work in this component, however,  more other complex component in ElementPlus depends their inner components and utils. Some components need nested slots to implement or strongly rely on a global popup component, their  parents or dependenies has to be checked twice to make sure everything goes fine. When you use more `flexible` way to achieve this,  you mustn't ignore both **logic** side and **view** side to check params or schema right, especially when they combines to provide a functionality.
3. The error boundaries could be fuzzy due to a mass of separate logic and views. Because of duck typing in view implementation, users can make their own logic which only need to match acceptable params of view. Lack of knowledge to build a component is waste of ElementPlus power and is more likely to create the morass to user themselves. In fact, the original implementation could be more tricky than users think.Once the logic can't run well, they will open issue to ask why things goes wrong. Or they can mix the origin and their own logic to create unimaginable disaster. All these potentail error has to be prevented in ElementPlus, and it's a exhausted thing to do.
4. The whole change to all components is also unrealistic. The breakchange will make user harder to accept or use.If you've had a good plan to do this, please provide your blueprint which settles all these problems.

**Suggestion**: In your case, you could make your own implementaion out of original Pagination.

**Comment by sxzz** [comment]
This is in line with Vue's philosophy, please control and obtain internal state only through props and ref.

**Comment by sxzz** [comment]
If you insist and can give a better example (which library uses the method you said), please feel free to open another discussion, we will consider again.
