### ISSUE TITLE
[Component] [message-box] el-config-provider设置的namespace="ep"，在ElMessageBox.confirm下渲染不完全，button和icon还是el-的class

### ISSUE THREAD

**Issue by imadentive** [element-plus/element-plus#11886]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.0-alpha.4`
- Element Plus Version: `2.2.35`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-message-box`

### Reproduction Link

[Link]()

### Steps to reproduce

<el-config-provider  namespace="ep">
...
</el-config-provider>
配置了namespace下使用ElMessageBox.confirm，渲染出来的html中部分class没有替换成ep，导致样式错乱

### What is Expected?

样式正确显示

### What is actually happening?

样式错乱

### Additional comments

_(empty)_

**Comment by jw-foss** [comment]
@imadentive next time please give us a valid reproducible demo for us to fix the issue, I'm aware of the bug is annoying you but we don't like bugs either, if there were any we need to fix it, and for helping us by providing a valid demo to reproduce the issue in the bug report is the only thing we'd ask from you guys.
