### ISSUE TITLE
[Component] [popover] [Bug Report] Behavior about Select in a Popover

### ISSUE THREAD

**Issue by GregLtrnr** [element-plus/element-plus#11904]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.35`
- Browser / OS: `Chrome 110.0.5481.177 / MacOS 12.6`
- Build Tool: `Vite`

### Related Component

- `el-popover`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuaW1wb3J0IHsgQ2xpY2tPdXRzaWRlIGFzIHZDbGlja091dHNpZGUgfSBmcm9tICdlbGVtZW50LXBsdXMnO1xuY29uc3QgaXNPcGVuID0gcmVmKGZhbHNlKTtcbmNvbnN0IHZhbHVlID0gcmVmKCcnKVxuZnVuY3Rpb24gY2xvc2UoKSB7XG5cdGlzT3Blbi52YWx1ZSA9IGZhbHNlO1xufVxuZnVuY3Rpb24gb3BlbigpIHtcbiAgaXNPcGVuLnZhbHVlID0gdHJ1ZTtcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXY+XG5cdFx0PGVsLWJ1dHRvbiBAY2xpY2s9XCJvcGVuXCI+Y2xpY2sgaGVyZTwvZWwtYnV0dG9uPlxuICAgIDxwPnt7wqBpc09wZW4gfX08L3A+XG5cdCAgPGVsLXBvcG92ZXIgOnZpc2libGU9XCJpc09wZW5cIiB2Q2xpY2tPdXRzaWRlPVwiY2xvc2VcIj5cbiAgICBcdDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuXHRcdFx0XHQ8cD48L3A+XG4gICAgXHQ8L3RlbXBsYXRlPlxuICAgIFx0PGRpdj5cbiAgICBcdCAgPEVsU2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiPlxuXHRcdFx0XHRcdDxFbE9wdGlvbiBsYWJlbD1cInRlc3RcIiBuYW1lPVwidGVzdFwiIHZhbHVlPVwidGVzdFwiPnRlc3Q8L0VsT3B0aW9uPlxuICAgICAgICAgIDxFbE9wdGlvbiBsYWJlbD1cInRlc3QyXCIgbmFtZT1cInRlc3QyXCIgdmFsdWU9XCJ0ZXN0MlwiPnRlc3QyPC9FbE9wdGlvbj5cbiAgICBcdCAgPC9FbFNlbGVjdD5cbiAgICBcdCAgPGJ1dHRvbiBAY2xpY2s9XCJjbG9zZVwiPkNhbmNlbDwvYnV0dG9uPlxuICAgXHRcdDwvZGl2PlxuICBcdDwvZWwtcG9wb3Zlcj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1 - Click `Open Popover`
2 - Open the select
3 - Click on a value

### What is Expected?

The value should be selected and the select is being closed after the click

### What is actually happening?

When clicking on one of the select values, the popover is being closed due to the v-click-outside

### Additional comments

In my case, I open the popover using a elDropdown item event, called with a @command passed on the elDropdown.
The popover is opening and if I click outside of the popover, it is being closed (I need this).
But when I click on one of the value of the select in the popover, the popover is being closed too whereas it shouldn't.
It seems that the v-click-outside dosen't work on the playground, but it does on my code.

**Comment by chenxch** [comment]
Didn't the demo you provided meet your expectations? `v-click-outside` doesn't work because you're hanging in the wrong place.

[playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuaW1wb3J0IHsgQ2xpY2tPdXRzaWRlIGFzIHZDbGlja091dHNpZGUgfSBmcm9tICdlbGVtZW50LXBsdXMnO1xuY29uc3QgaXNPcGVuID0gcmVmKGZhbHNlKTtcbmNvbnN0IHZhbHVlID0gcmVmKCcnKVxuY29uc3QgZWwgPSByZWYobnVsbClcbmZ1bmN0aW9uIGNsb3NlKGUpIHtcbiAgY29uc29sZS5sb2coZWwudmFsdWUpXG4gIGlmKGVsLnZhbHVlLmNvbnRhaW5zKGUudGFyZ2V0KSl7XG5cdFx0cmV0dXJuIFxuICB9XG4gIGNvbnNvbGUubG9nKGUpXG5cdGlzT3Blbi52YWx1ZSA9IGZhbHNlO1xufVxuZnVuY3Rpb24gb3BlbigpIHtcbiAgaXNPcGVuLnZhbHVlID0gdHJ1ZTtcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXY+XG5cdFx0PGVsLWJ1dHRvbiBAY2xpY2s9XCJvcGVuXCI+Y2xpY2sgaGVyZTwvZWwtYnV0dG9uPlxuICAgIDxwPnt7wqBpc09wZW4gfX08L3A+XG5cdCAgPGVsLXBvcG92ZXIgOnZpc2libGU9XCJpc09wZW5cIj5cbiAgICBcdDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuXHRcdFx0XHQ8cD48L3A+XG4gICAgXHQ8L3RlbXBsYXRlPlxuICAgIFx0PGRpdiByZWY9XCJlbFwiIHYtY2xpY2stb3V0c2lkZT1cImNsb3NlXCIgY2xhc3M9XCJ0ZXN0XCI+XG4gICAgXHQgIDxFbFNlbGVjdCB2LW1vZGVsPVwidmFsdWVcIiA6dGVsZXBvcnRlZD1cImZhbHNlXCI+XG5cdFx0XHRcdFx0PEVsT3B0aW9uIGxhYmVsPVwidGVzdFwiIG5hbWU9XCJ0ZXN0XCIgdmFsdWU9XCJ0ZXN0XCI+dGVzdDwvRWxPcHRpb24+XG4gICAgICAgICAgPEVsT3B0aW9uIGxhYmVsPVwidGVzdDJcIiBuYW1lPVwidGVzdDJcIiB2YWx1ZT1cInRlc3QyXCI+dGVzdDI8L0VsT3B0aW9uPlxuICAgIFx0ICA8L0VsU2VsZWN0PlxuICAgIFx0ICA8YnV0dG9uIEBjbGljaz1cImNsb3NlXCI+Q2FuY2VsPC9idXR0b24+XG4gICBcdFx0PC9kaXY+XG4gIFx0PC9lbC1wb3BvdmVyPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)
I think your problem should be v-click-outside not working.

**Comment by GregLtrnr** [comment]
Ok I see where was the problem, my select was teleported out of my div and I didn't check the event target, thanks for the help you are saving my day !
