### ISSUE TITLE
[Feature Request] Whether the Option component considers adding a null type

### ISSUE THREAD

**Issue by wukang0718** [element-plus/element-plus#1206]
### Existing Component
Yes

### Component Name
Options

### Description
Whether the Option component considers adding a null type
![image](https://user-images.githubusercontent.com/42261663/103733483-cdfeba80-5024-11eb-9293-862604e5add6.png)

**Comment by zazzaz** [comment]
Can you please check the latest version of element-plus. This should have been fixed in it.

**Comment by wukang0718** [comment]
I have read version `1.0.1-beta.21`, which is the definition of value prop
```
value: {
  required: true,
  type: [String, Number, Object],
}
```
null is not currently supported

**Comment by JeremyWuuuuu** [comment]
Maybe we can do that, but may I ask why you'd need null type?

**Comment by wukang0718** [comment]
The value of this parameter should be null or not at all when selecting all

**Comment by Ryan2128** [comment]
Vue's props validator does not support type as `null`. You can use a empty string instead of it.

![image](https://user-images.githubusercontent.com/33176053/103896376-d6dab380-512c-11eb-9ce6-f26248a03cca.png)


![image](https://user-images.githubusercontent.com/33176053/103896396-dd692b00-512c-11eb-9ea2-42030c50f612.png)


@wukang0718

**Comment by wukang0718** [comment]
To understand the.
If type is not set, null can be passed without warning

**Comment by Ryan2128** [comment]
The `null` in JavaScript represents empty, I think you should use a special value to indicate select all just like a string or an empty string.

**Comment by alex-outsourci** [comment]
@Ryan2128 for "all", "any" and similar options it much better to use null, because it is common for different types of options (strings, numbers etc, boolean) and when you pass data to server, `null` value much easier to handle with rule like `nullable`.

i.e you have options of boolean type, let's imagine select has 3 values ("any": null, "yes": true, "no": false), so without null value you cann't easy validate boolean type, because you need some string value to send like "any" or "all" but in case with "null" you can have "nullable" rule for validation which covers option' types.
