### ISSUE TITLE
[Component] [date-picker] el-date-picker type="datetimerange"  format="YYYY-MM-DD" 下拉框中时分秒显示不正确

### ISSUE THREAD

**Issue by smallShy** [element-plus/element-plus#12431]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.2`
- Browser / OS: `chrome  111.0.5563.148 / window 10`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[CodePen](https://codepen.io/smallshy/pen/PoyZGmr)

### Steps to reproduce

页面展示时，只显示年月日，但是下拉中需要选择时分秒。使用了 format="YYYY-MM-DD" 导致下拉中的时分秒显示不正确。

### What is Expected?

时分秒可以正确选择，并且页面显示中只有年月日

### What is actually happening?

时分秒显示区域未格式化

### Additional comments

_(empty)_

![datepicker](https://user-images.githubusercontent.com/75575779/231709305-63a29b62-2813-4fda-8671-ffc641afdef3.jpg)
![Snipaste_2023-04-13_16-56-14](https://user-images.githubusercontent.com/75575779/231709339-418940a1-589e-4bd7-9d72-7aa6b463371a.jpg)

**Comment by chenxch** [comment]
那使用 `daterange`是不是会更符合你的实际需求？

**Comment by smallShy** [comment]
> 那使用 `daterange`是不是会更符合你的实际需求？

不行，需求是得选择时分秒，但是显示年月日

**Comment by 2048920439** [comment]
Date转YYYY-MM-DD肯定会丢失时间的,这个你自己用外部变量实现比较靠谱

**Comment by tolking** [comment]
After 2.4.0, you can use the `time-format` attribute to configure the format of the time

[demo](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKFtdKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWRhdGUtcGlja2VyXG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICB0eXBlPVwiZGF0ZXRpbWVyYW5nZVwiXG4gICAgcmFuZ2Utc2VwYXJhdG9yPVwiVG9cIlxuICAgIHN0YXJ0LXBsYWNlaG9sZGVyPVwiU3RhcnQgZGF0ZVwiXG4gICAgZW5kLXBsYWNlaG9sZGVyPVwiRW5kIGRhdGVcIlxuICAgIGZvcm1hdD1cIllZWVktTU0tRERcIlxuICAgIHRpbWUtZm9ybWF0PVwiIFwiXG4gIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

Fixed by #14330
