### ISSUE TITLE
[Component] [date-picker] el-date-picker 展示问题

### ISSUE THREAD

**Issue by smallShy** [element-plus/element-plus#12859]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.2`
- Browser / OS: `chrome  111.0.5563.148 / window 10`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[CodePen](https://codepen.io/smallshy/pen/dyggZmN)

### Steps to reproduce

type="datetimerange"。用户选择具体的时间后，弹出框中显示未格式化。format字段表示显示在输入框中的格式。是不是可以增加一个属性，表示用户选择完成之后，显示在页面的格式

### What is Expected?

最后选择完成后，页面显示YYYY-MM-DD

### What is actually happening?

format虽然也可以显示YYYY-MM-DD，但是再次选择时分秒格式不对

### Additional comments

_(empty)_

![image](https://github.com/element-plus/element-plus/assets/75575779/97ee113b-2d5c-4531-8f44-d8887c6a54b1)

**Comment by wonderl17** [comment]
自定义format的话，如果这样设置呢：
format="YYYY-MM-DD hh:mm:ss"

**Comment by smallShy** [comment]
> 自定义format的话，如果这样设置呢： format="YYYY-MM-DD hh:mm:ss"

这样设置的话，页面显示也会显示时分秒。需求是选择年月日时分秒后，页面仅显示年月日

**Comment by mmmmr** [comment]
value-format

**Comment by nideajun** [comment]
el-date-picker 和 el-select 以及  el-input  宽度不一致呢，显得特别的难看，想不用el又舍不得，用嘛对不齐超难看。

**Comment by tolking** [comment]
After 2.4.0, you can use the `time-format` attribute to configure the format of the time

[demo](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKFtdKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWRhdGUtcGlja2VyXG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICB0eXBlPVwiZGF0ZXRpbWVyYW5nZVwiXG4gICAgcmFuZ2Utc2VwYXJhdG9yPVwiVG9cIlxuICAgIHN0YXJ0LXBsYWNlaG9sZGVyPVwiU3RhcnQgZGF0ZVwiXG4gICAgZW5kLXBsYWNlaG9sZGVyPVwiRW5kIGRhdGVcIlxuICAgIGZvcm1hdD1cIllZWVktTU0tRERcIlxuICAgIHRpbWUtZm9ybWF0PVwiIFwiXG4gIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

Fixed by #14330

**Comment by nideajun** [comment]
好的谢谢，好像新版已经看到是对齐了。
&nbsp;


浪箭
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月13日(星期五) 下午5:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [element-plus/element-plus] [Component] [date-picker] el-date-picker 展示问题 (Issue #12859)





 
After 2.4.0, you can use the time-format attribute to configure the format of the time
 
demo
 
Fixed by #14330
