### ISSUE TITLE
[Feature Request] NavMenu(Top bar) responsive feature

### ISSUE THREAD

**Issue by WKJay** [element-plus/element-plus#1308]
### Existing Component
Yes

### Component Name
NavMenu

### Description
Is it possible to add responsive feature for NavMenu(top bar) like bootstrap NavBar？
Here is the sample: https://getbootstrap.com/docs/5.0/components/navbar/#supported-content

**Comment by JeremyWuuuuu** [comment]
Well, `NavBar` isn't controlled by `media query` in `ElementPlus`, to manage to do so, you can use `ResizeObserver` to listen to the `body` element, when it changes you modify the binding value to `NavBar`, so that you can manage to do that. We didn't implement that for some reasons, you can implement this feature on you own based on the method I just described above.

**Comment by JeremyWuuuuu** [comment]
Note that `ElementPlus` is still a `desktop` first library, so we keep responsive in a reasonable range.

**Comment by WKJay** [comment]
@JeremyWuuuuu Understood. Thanks for your reply.

**Comment by JeremyWuuuuu** [comment]
NP, feel free to ping me if you have any problem.
