### ISSUE TITLE
[Bug Report]  Use on-demand import in typescript and Vue projects, but the element has no style. 

### ISSUE THREAD

**Issue by HealerLZH** [element-plus/element-plus#1392]
### Element Plus version
1.0.2-beta.30

### OS/Browsers version
win10

### Vue version
3.0.5

### Reproduction Link
https://github.com/HealerLZH/elementPlus-vue-ts

### Steps to reproduce
npm install
npm run serve

Then you can see that there is no style for buttons on the page

### What is Expected?
Introducing elementplus into ts and Vue as needed

### What is actually happening?
there is no style for buttons on the page

**Comment by zazzaz** [comment]
please use babel-plugin-component to load style on demand https://element-plus.org/#/en-US/component/quickstart#on-demand

or, just import the style 

import 'element-plus/lib/theme-chalk/index.css';

**Comment by HealerLZH** [comment]
```
{
    "plugins": [
      [
        "component",
        {
          "libraryName": "element-plus",
          "styleLibraryName": "theme-chalk",
          "style":true
        }
      ]
    ]
  }
```
thanks,Just like the demo I submitted(https://github.com/HealerLZH/elementPlus-vue-ts). I've used Babel-plugin-component,The element was imported, but the style didn't work.

**Comment by HealerLZH** [comment]
I found that if there is no ts in the project, the style is OK. Then, you don't need to import 'element plus / lib / theme talk separately/ index.css ';）

**Comment by zazzaz** [comment]
please make sure your ts file is finally processed by babel-loader to use this plugin

**Comment by JeremyWuuuuu** [comment]
This could be caused by your build tools, you said that when no `.ts` files everything was fine, this plugin was written in `babel-plugin` so you need to process your file with `babel` instead of any other compliers like `typescript`, check this out: 
https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-typescript, you can specify how to process your file with `vue.config.js`.

**Comment by JeremyWuuuuu** [comment]
Well, I believe this was caused by the `babel-plugin-component` we will fix that.

**Comment by JeremyWuuuuu** [comment]
In case that you are curious about this issue, I'll explain this as simple as possible.
So essentially the plugin dose things like this:
![image](https://user-images.githubusercontent.com/15975785/106431489-4b90db80-64a8-11eb-93b0-84e053ff7dfa.png)
And now days, `ESModule` were used almost everywhere, when in `CommonJS` mode, the plugin transpiles code like the screenshot above.
But for `ESModule` it transpiles the code like this:
![image](https://user-images.githubusercontent.com/15975785/106432022-146efa00-64a9-11eb-9adc-5e986215d782.png)
In this case, the statement `import variableName from '/path/to/file.css` will not inject `style` tag into the document. So that we ended up with no styles.
So the solution is rather simple, either we develop a new plugin for that. either we modified the previous plugin.
NOTE THAT THIS IS NOT ONLY CAUSE BY TYPESCRIPT, if you have `.js` file with transplier like `babel` which does not transpiler your code into `commonjs`, you will end up the same issue.

**Comment by JeremyWuuuuu** [comment]
So I have come up with a fix:
Firstly, you remove `babel-plugin-component` via 
```shell
$ yarn remove babel-plugin-component
``` 
or 
```shell
$ npm uninstall babel-plugin-component
```
Then add plugin:

```shell
$ yarn add babel-plugin-import -D
```
or 
```shell
$ npm install babel-plugin-import -D
```

then you need to modify your `babel.config.js` file:
#### babel.config.js
```js
module.exports = {
  // ... other configs
  plugins: [
    [
      "import",
      {
        libraryName: "element-plus",
        customStyleName: (name, file) => {
          return `element-plus/lib/theme-chalk/${name}.css`;
        },
      },
    ],
  ],
}
```

In you case you are using `vue-cli3`, so you also need to do the following steps:
#### 1. Generate `vue.config.js`
```shell
# at the root path of you project
$ touch vue.config.js
```

#### 2. Edit `vue.config.js` with your editor with content:

Ensure you have `@babel/core@latest babel-loader@latest ` installed.

```js
module.exports = {
  // other configs.
  chainWebpack: (config) => {
    config.module
      .rule("ts")
      .use("babel-loader")
      .loader("babel-loader")
  },
  // other configs.
};
```

**Comment by JeremyWuuuuu** [comment]
I will update our documentations later.

**Comment by HealerLZH** [comment]
Thank you for your help. I will try to verify your method later.
Thanks again

**Comment by mPyth** [comment]
@JeremyWuuuuu could you please update documentation. I've tried instructions you suggested here, but not successfully. I've added comment on https://github.com/element-plus/element-plus/issues/1492#issuecomment-807370689 .
I'm using SCSS (dart version) and typescript and need on demand importing. I've understand the only way to do it is to install packages `element-theme` and `element-theme-chalk`. Am I right ?
I was not able to install `element-theme` (I'll probably open new ticket).

**Comment by Ryan2128** [comment]
> @JeremyWuuuuu could you please update documentation. I've tried instructions you suggested here, but not successfully. I've added comment on [#1492 (comment)](https://github.com/element-plus/element-plus/issues/1492#issuecomment-807370689) .
> I'm using SCSS (dart version) and typescript and need on demand importing. I've understand the only way to do it is to install packages `element-theme` and `element-theme-chalk`. Am I right ?
> I was not able to install `element-theme` (I'll probably open new ticket).

Please check #1672
