### ISSUE TITLE
[Style] [collapse-item, collapse] When the el-collapse-item is in the contracted state, it triggers mouseenter and cannot display custom icons

### ISSUE THREAD

**Issue by Bruse-Lee** [element-plus/element-plus#13924]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.0`
- Element Plus Version: `2.2.0`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-collapse-item`
- `el-collapse`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiwgcmVhY3RpdmUgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzLCBFZGl0IH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcblxuY29uc3QgYWN0aXZlTmFtZSA9IHJlZignRGFzaGJvYXJkJylcbmNvbnN0IHNob3dQYXJlbnRFZGl0QnV0dG9uID0gcmVhY3RpdmUoe30pXG5jb25zdCBkYXRhTWFwID0gcmVhY3RpdmUoe1xuICBkZWZhdWx0UHJvcHM6IHtcbiAgICBjaGlsZHJlbjogJ2NoaWxkcmVuJyxcbiAgICBsYWJlbDogJ2xhYmVsJyxcbiAgfSxcbiAgcG93ZXJEYXRhOiBbXG4gICAge1xuICAgICAgaWQ6IDEsXG4gICAgICBuYW1lOiAnRGFzaGJvYXJkJyxcbiAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgIHtcbiAgICAgICAgICBpZDogMjIsXG4gICAgICAgICAgcGlkOiAxLFxuICAgICAgICAgIG5hbWU6ICdob21lJ1xuICAgICAgICB9XG4gICAgICBdXG4gICAgfSxcbiAgICB7XG4gICAgICBpZDogMixcbiAgICAgIG5hbWU6ICdBZG1pbicsXG4gICAgICBjaGlsZHJlbjogW1xuICAgICAgICB7XG4gICAgICAgICAgaWQ6IDI0LFxuICAgICAgICAgIHBpZDogMixcbiAgICAgICAgICBuYW1lOiAnbWVudSdcbiAgICAgICAgfSxcbiAgICAgICAge1xuICAgICAgICAgIGlkOiAyNSxcbiAgICAgICAgICBwaWQ6IDIsXG4gICAgICAgICAgbmFtZTogJ3JvdXRlcidcbiAgICAgICAgfSxcbiAgICAgICAge1xuICAgICAgICAgIGlkOiAyNixcbiAgICAgICAgICBwaWQ6IDIsXG4gICAgICAgICAgbmFtZTogJ2F1ZGl0J1xuICAgICAgICB9XG4gICAgICBdXG4gICAgfSxcbiAgXSxcbiAgY2hpbGREYXRhOiBbXSxcbiAgcm91dGVyVHJlZVRhYmxlTGlzdDogW10sXG4gIGNoaWxkcmVuTWVudU9wdGlvbjogW10sXG59KVxubGV0IGRhdGFUcmVlUmVmID0gcmVmKFtdKVxuXG5jb25zdCBoYW5kbGVQYXJlbnRNb3VzZUVudGVyID0gKGl0ZW0pID0+IHtcbiAgY29uc29sZS5sb2coJ2VudGVyJylcbiAgc2hvd1BhcmVudEVkaXRCdXR0b25baXRlbS5pZF0gPSB0cnVlXG4gIGNvbnNvbGUubG9nKGl0ZW0pXG59XG5cbmNvbnN0IGhhbmRsZVBhcmVudE1vdXNlTGVhdmUgPSAoaXRlbSkgPT4ge1xuICBjb25zb2xlLmxvZygnbGVhdmUnKVxuICBzaG93UGFyZW50RWRpdEJ1dHRvbltpdGVtLmlkXSA9IGZhbHNlXG59XG5cbmNvbnN0IGZpbHRlck5vZGUgPSAodmFsdWUsIGRhdGEpID0+IHtcbiAgcmV0dXJuIGRhdGEudHlwZSA9PSAxXG59XG5cbmNvbnN0IHNldFRyZWVSZWYgPSAoZWwpID0+IHtcbiAgaWYgKGVsKSB7XG4gICAgZGF0YVRyZWVSZWYudmFsdWUucHVzaChlbClcbiAgfVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWNvbGxhcHNlIHYtbW9kZWw9XCJhY3RpdmVOYW1lXCI+XG4gICAgPCEtLSDkvb/nlKh2LWZvcuW+queOr+a4suafk2VsLWNvbGxhcHNlLWl0ZW0gLS0+XG4gICAgPGVsLWNvbGxhcHNlLWl0ZW0gY2xhc3M9XCJlbC1jb2xsYXBzZS1pdGVtLWVsZVwiIHYtZm9yPVwiaXRlbSBpbiBkYXRhTWFwLnBvd2VyRGF0YVwiIDprZXk9XCJpdGVtLmlkXCIgOnRpdGxlPVwiaXRlbS5uYW1lXCJcbiAgICAgIDpuYW1lPVwiaXRlbS5uYW1lXCIgQG1vdXNlZW50ZXIuc3RvcD1cImhhbmRsZVBhcmVudE1vdXNlRW50ZXIoaXRlbSlcIiBAbW91c2VsZWF2ZS5zdG9wPVwiaGFuZGxlUGFyZW50TW91c2VMZWF2ZShpdGVtKVwiPlxuICAgICAgPGVsLXRyZWUgY2xhc3M9XCJsZWZ0X3RyZWVcIiA6ZGF0YT1cIml0ZW0uY2hpbGRyZW5cIiBoaWdobGlnaHQtY3VycmVudCA6ZmlsdGVyLW5vZGUtbWV0aG9kPVwiZmlsdGVyTm9kZVwiXG4gICAgICAgIDpwcm9wcz1cImRhdGFNYXAuZGVmYXVsdFByb3BzXCIgbm9kZS1rZXk9XCJpZFwiIDpyZWY9XCJzZXRUcmVlUmVmXCI+XG4gICAgICAgIDwhLS0gZWwtdHJlZeeahOiKgueCueaooeadvyAtLT5cbiAgICAgICAgPCEtLSBlbC10cmVlJ3Mgbm9kZSB0ZW1wbGF0ZSAtLT5cbiAgICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwieyBub2RlLCBkYXRhIH1cIj5cbiAgICAgICAgICA8ZGl2IGNsYXNzPVwiY3VzdG9tLXRyZWUtbm9kZVwiPlxuICAgICAgICAgICAgPHNwYW4gY2xhc3M9XCJ0cmVlLWNvbnRlbnQtbmFtZVwiIHYtaWY9XCJkYXRhLnBpZCA+IDBcIj57eyBkYXRhLm5hbWUgfX08L3NwYW4+XG4gICAgICAgICAgICA8c3BhbiBjbGFzcz1cInRyZWUtY29udGVudC1uYW1lXCIgdi1lbHNlPnt7IGRhdGEubmFtZSB9fTwvc3Bhbj5cbiAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIDwvZWwtdHJlZT5cbiAgICAgIDwhLS0g6L+Z5pi+56S655qE5piv54i257qn6I+c5Y2V55qE57yW6L6R5oyJ6ZKuIC0tPlxuICAgICAgPGVsLWJ1dHRvbiBjbGFzcz1cInBhcmVudC1tZW51LWVkaXQtYnV0dG9uXCIgc2l6ZT1cInNtYWxsXCIgdi1zaG93PVwic2hvd1BhcmVudEVkaXRCdXR0b25baXRlbS5pZF1cIiA6aWNvbj1cIkVkaXRcIlxuICAgICAgICB0eXBlPVwicHJpbWFyeVwiPkVkaXQ8L2VsLWJ1dHRvbj5cbiAgICA8L2VsLWNvbGxhcHNlLWl0ZW0+XG4gIDwvZWwtY29sbGFwc2U+XG48L3RlbXBsYXRlPlxuXG48c3R5bGU+XG4uZWwtY29sbGFwc2UtaXRlbS5lbC1jb2xsYXBzZS1pdGVtLWVsZSB7XG4gIHBvc2l0aW9uOiByZWxhdGl2ZTtcbn1cblxuLnBhcmVudC1tZW51LWVkaXQtYnV0dG9uIHtcbiAgY3Vyc29yOiBwb2ludGVyO1xuICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gIHRvcDogMTJweDtcbiAgcmlnaHQ6IDcwcHg7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

<el-collapse-item
                    class="el-collapse-item-ele"
                    v-for="item in dataMap.powerData"
                    :key="item.id"
                    :title="item.name"
                    :name="item.name"
                    @mouseenter.stop="handleParentMouseEnter(item)"
                    @mouseleave.stop="handleParentMouseLeave(item)"
                >
 </el-collapse-item>

### What is Expected?

When el-collapse-item is in the contracted state, trigger mouseenter to display custom icons

### What is actually happening?

When the el-collapse-item is in the contracted state, it cannot trigger mouseenter to display the custom icon. The custom icon is only displayed when it is expanded. The @mouseenter event has already been triggered.

### Additional comments

_(empty)_

**Comment by Bruse-Lee** [comment]
wuwu～ Help me !

**Comment by yj-liuzepeng** [comment]
I suggest you set up this edit button through [custom title](https://element-plus.gitee.io/en-US/component/collapse.html#custom-title) instead of using position, like [Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiwgcmVhY3RpdmUgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzLCBFZGl0IH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcblxuY29uc3QgYWN0aXZlTmFtZSA9IHJlZignRGFzaGJvYXJkJylcbmNvbnN0IHNob3dQYXJlbnRFZGl0QnV0dG9uID0gcmVhY3RpdmUoe30pXG5jb25zdCBkYXRhTWFwID0gcmVhY3RpdmUoe1xuICBkZWZhdWx0UHJvcHM6IHtcbiAgICBjaGlsZHJlbjogJ2NoaWxkcmVuJyxcbiAgICBsYWJlbDogJ2xhYmVsJyxcbiAgfSxcbiAgcG93ZXJEYXRhOiBbXG4gICAge1xuICAgICAgaWQ6IDEsXG4gICAgICBuYW1lOiAnRGFzaGJvYXJkJyxcbiAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgIHtcbiAgICAgICAgICBpZDogMjIsXG4gICAgICAgICAgcGlkOiAxLFxuICAgICAgICAgIG5hbWU6ICdob21lJ1xuICAgICAgICB9XG4gICAgICBdXG4gICAgfSxcbiAgICB7XG4gICAgICBpZDogMixcbiAgICAgIG5hbWU6ICdBZG1pbicsXG4gICAgICBjaGlsZHJlbjogW1xuICAgICAgICB7XG4gICAgICAgICAgaWQ6IDI0LFxuICAgICAgICAgIHBpZDogMixcbiAgICAgICAgICBuYW1lOiAnbWVudSdcbiAgICAgICAgfSxcbiAgICAgICAge1xuICAgICAgICAgIGlkOiAyNSxcbiAgICAgICAgICBwaWQ6IDIsXG4gICAgICAgICAgbmFtZTogJ3JvdXRlcidcbiAgICAgICAgfSxcbiAgICAgICAge1xuICAgICAgICAgIGlkOiAyNixcbiAgICAgICAgICBwaWQ6IDIsXG4gICAgICAgICAgbmFtZTogJ2F1ZGl0J1xuICAgICAgICB9XG4gICAgICBdXG4gICAgfSxcbiAgXSxcbiAgY2hpbGREYXRhOiBbXSxcbiAgcm91dGVyVHJlZVRhYmxlTGlzdDogW10sXG4gIGNoaWxkcmVuTWVudU9wdGlvbjogW10sXG59KVxubGV0IGRhdGFUcmVlUmVmID0gcmVmKFtdKVxuXG5jb25zdCBoYW5kbGVQYXJlbnRNb3VzZUVudGVyID0gKGl0ZW0pID0+IHtcbiAgY29uc29sZS5sb2coJ2VudGVyJylcbiAgc2hvd1BhcmVudEVkaXRCdXR0b25baXRlbS5pZF0gPSB0cnVlXG4gIGNvbnNvbGUubG9nKGl0ZW0pXG59XG5cbmNvbnN0IGhhbmRsZVBhcmVudE1vdXNlTGVhdmUgPSAoaXRlbSkgPT4ge1xuICBjb25zb2xlLmxvZygnbGVhdmUnKVxuICBzaG93UGFyZW50RWRpdEJ1dHRvbltpdGVtLmlkXSA9IGZhbHNlXG59XG5cbmNvbnN0IGZpbHRlck5vZGUgPSAodmFsdWUsIGRhdGEpID0+IHtcbiAgcmV0dXJuIGRhdGEudHlwZSA9PSAxXG59XG5cbmNvbnN0IHNldFRyZWVSZWYgPSAoZWwpID0+IHtcbiAgaWYgKGVsKSB7XG4gICAgZGF0YVRyZWVSZWYudmFsdWUucHVzaChlbClcbiAgfVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWNvbGxhcHNlIHYtbW9kZWw9XCJhY3RpdmVOYW1lXCI+XG4gICAgPCEtLSDkvb/nlKh2LWZvcuW+queOr+a4suafk2VsLWNvbGxhcHNlLWl0ZW0gLS0+XG4gICAgPGVsLWNvbGxhcHNlLWl0ZW0gY2xhc3M9XCJlbC1jb2xsYXBzZS1pdGVtLWVsZVwiIHYtZm9yPVwiaXRlbSBpbiBkYXRhTWFwLnBvd2VyRGF0YVwiIDprZXk9XCJpdGVtLmlkXCIgOnRpdGxlPVwiaXRlbS5uYW1lXCJcbiAgICAgIDpuYW1lPVwiaXRlbS5uYW1lXCIgQG1vdXNlZW50ZXIuc3RvcD1cImhhbmRsZVBhcmVudE1vdXNlRW50ZXIoaXRlbSlcIiBAbW91c2VsZWF2ZS5zdG9wPVwiaGFuZGxlUGFyZW50TW91c2VMZWF2ZShpdGVtKVwiPlxuICAgICAgPGVsLXRyZWUgY2xhc3M9XCJsZWZ0X3RyZWVcIiA6ZGF0YT1cIml0ZW0uY2hpbGRyZW5cIiBoaWdobGlnaHQtY3VycmVudCA6ZmlsdGVyLW5vZGUtbWV0aG9kPVwiZmlsdGVyTm9kZVwiXG4gICAgICAgIDpwcm9wcz1cImRhdGFNYXAuZGVmYXVsdFByb3BzXCIgbm9kZS1rZXk9XCJpZFwiIDpyZWY9XCJzZXRUcmVlUmVmXCI+XG4gICAgICAgIDwhLS0gZWwtdHJlZeeahOiKgueCueaooeadvyAtLT5cbiAgICAgICAgPCEtLSBlbC10cmVlJ3Mgbm9kZSB0ZW1wbGF0ZSAtLT5cbiAgICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwieyBub2RlLCBkYXRhIH1cIj5cbiAgICAgICAgICA8ZGl2IGNsYXNzPVwiY3VzdG9tLXRyZWUtbm9kZVwiPlxuICAgICAgICAgICAgPHNwYW4gY2xhc3M9XCJ0cmVlLWNvbnRlbnQtbmFtZVwiIHYtaWY9XCJkYXRhLnBpZCA+IDBcIj57eyBkYXRhLm5hbWUgfX08L3NwYW4+XG4gICAgICAgICAgICA8c3BhbiBjbGFzcz1cInRyZWUtY29udGVudC1uYW1lXCIgdi1lbHNlPnt7IGRhdGEubmFtZSB9fTwvc3Bhbj5cbiAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIDwvZWwtdHJlZT5cbiAgICAgIDx0ZW1wbGF0ZSAjdGl0bGU+XG4gICAgICAgIENvbnNpc3RlbmN5IDxlbC1idXR0b24gc2l6ZT1cInNtYWxsXCIgdHlwZT1cInByaW1hcnlcIiB2LXNob3c9XCJzaG93UGFyZW50RWRpdEJ1dHRvbltpdGVtLmlkXVwiPnRlc3QtZWRpdDwvZWwtYnV0dG9uPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIDwhLS0g6L+Z5pi+56S655qE5piv54i257qn6I+c5Y2V55qE57yW6L6R5oyJ6ZKuIC0tPlxuICAgICAgPGVsLWJ1dHRvbiBjbGFzcz1cInBhcmVudC1tZW51LWVkaXQtYnV0dG9uXCIgc2l6ZT1cInNtYWxsXCIgdi1zaG93PVwic2hvd1BhcmVudEVkaXRCdXR0b25baXRlbS5pZF1cIiA6aWNvbj1cIkVkaXRcIlxuICAgICAgICB0eXBlPVwicHJpbWFyeVwiPkVkaXQ8L2VsLWJ1dHRvbj5cbiAgICA8L2VsLWNvbGxhcHNlLWl0ZW0+XG4gIDwvZWwtY29sbGFwc2U+XG48L3RlbXBsYXRlPlxuXG48c3R5bGU+XG4uZWwtY29sbGFwc2UtaXRlbS5lbC1jb2xsYXBzZS1pdGVtLWVsZSB7XG4gIHBvc2l0aW9uOiByZWxhdGl2ZTtcbn1cblxuLnBhcmVudC1tZW51LWVkaXQtYnV0dG9uIHtcbiAgY3Vyc29yOiBwb2ludGVyO1xuICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gIHRvcDogMTJweDtcbiAgcmlnaHQ6IDcwcHg7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

**Comment by Bruse-Lee** [comment]
> I suggest you set up this edit button through [custom title](https://element-plus.gitee.io/en-US/component/collapse.html#custom-title) instead of using position, like [Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiwgcmVhY3RpdmUgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzLCBFZGl0IH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcblxuY29uc3QgYWN0aXZlTmFtZSA9IHJlZignRGFzaGJvYXJkJylcbmNvbnN0IHNob3dQYXJlbnRFZGl0QnV0dG9uID0gcmVhY3RpdmUoe30pXG5jb25zdCBkYXRhTWFwID0gcmVhY3RpdmUoe1xuICBkZWZhdWx0UHJvcHM6IHtcbiAgICBjaGlsZHJlbjogJ2NoaWxkcmVuJyxcbiAgICBsYWJlbDogJ2xhYmVsJyxcbiAgfSxcbiAgcG93ZXJEYXRhOiBbXG4gICAge1xuICAgICAgaWQ6IDEsXG4gICAgICBuYW1lOiAnRGFzaGJvYXJkJyxcbiAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgIHtcbiAgICAgICAgICBpZDogMjIsXG4gICAgICAgICAgcGlkOiAxLFxuICAgICAgICAgIG5hbWU6ICdob21lJ1xuICAgICAgICB9XG4gICAgICBdXG4gICAgfSxcbiAgICB7XG4gICAgICBpZDogMixcbiAgICAgIG5hbWU6ICdBZG1pbicsXG4gICAgICBjaGlsZHJlbjogW1xuICAgICAgICB7XG4gICAgICAgICAgaWQ6IDI0LFxuICAgICAgICAgIHBpZDogMixcbiAgICAgICAgICBuYW1lOiAnbWVudSdcbiAgICAgICAgfSxcbiAgICAgICAge1xuICAgICAgICAgIGlkOiAyNSxcbiAgICAgICAgICBwaWQ6IDIsXG4gICAgICAgICAgbmFtZTogJ3JvdXRlcidcbiAgICAgICAgfSxcbiAgICAgICAge1xuICAgICAgICAgIGlkOiAyNixcbiAgICAgICAgICBwaWQ6IDIsXG4gICAgICAgICAgbmFtZTogJ2F1ZGl0J1xuICAgICAgICB9XG4gICAgICBdXG4gICAgfSxcbiAgXSxcbiAgY2hpbGREYXRhOiBbXSxcbiAgcm91dGVyVHJlZVRhYmxlTGlzdDogW10sXG4gIGNoaWxkcmVuTWVudU9wdGlvbjogW10sXG59KVxubGV0IGRhdGFUcmVlUmVmID0gcmVmKFtdKVxuXG5jb25zdCBoYW5kbGVQYXJlbnRNb3VzZUVudGVyID0gKGl0ZW0pID0+IHtcbiAgY29uc29sZS5sb2coJ2VudGVyJylcbiAgc2hvd1BhcmVudEVkaXRCdXR0b25baXRlbS5pZF0gPSB0cnVlXG4gIGNvbnNvbGUubG9nKGl0ZW0pXG59XG5cbmNvbnN0IGhhbmRsZVBhcmVudE1vdXNlTGVhdmUgPSAoaXRlbSkgPT4ge1xuICBjb25zb2xlLmxvZygnbGVhdmUnKVxuICBzaG93UGFyZW50RWRpdEJ1dHRvbltpdGVtLmlkXSA9IGZhbHNlXG59XG5cbmNvbnN0IGZpbHRlck5vZGUgPSAodmFsdWUsIGRhdGEpID0+IHtcbiAgcmV0dXJuIGRhdGEudHlwZSA9PSAxXG59XG5cbmNvbnN0IHNldFRyZWVSZWYgPSAoZWwpID0+IHtcbiAgaWYgKGVsKSB7XG4gICAgZGF0YVRyZWVSZWYudmFsdWUucHVzaChlbClcbiAgfVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWNvbGxhcHNlIHYtbW9kZWw9XCJhY3RpdmVOYW1lXCI+XG4gICAgPCEtLSDkvb/nlKh2LWZvcuW+queOr+a4suafk2VsLWNvbGxhcHNlLWl0ZW0gLS0+XG4gICAgPGVsLWNvbGxhcHNlLWl0ZW0gY2xhc3M9XCJlbC1jb2xsYXBzZS1pdGVtLWVsZVwiIHYtZm9yPVwiaXRlbSBpbiBkYXRhTWFwLnBvd2VyRGF0YVwiIDprZXk9XCJpdGVtLmlkXCIgOnRpdGxlPVwiaXRlbS5uYW1lXCJcbiAgICAgIDpuYW1lPVwiaXRlbS5uYW1lXCIgQG1vdXNlZW50ZXIuc3RvcD1cImhhbmRsZVBhcmVudE1vdXNlRW50ZXIoaXRlbSlcIiBAbW91c2VsZWF2ZS5zdG9wPVwiaGFuZGxlUGFyZW50TW91c2VMZWF2ZShpdGVtKVwiPlxuICAgICAgPGVsLXRyZWUgY2xhc3M9XCJsZWZ0X3RyZWVcIiA6ZGF0YT1cIml0ZW0uY2hpbGRyZW5cIiBoaWdobGlnaHQtY3VycmVudCA6ZmlsdGVyLW5vZGUtbWV0aG9kPVwiZmlsdGVyTm9kZVwiXG4gICAgICAgIDpwcm9wcz1cImRhdGFNYXAuZGVmYXVsdFByb3BzXCIgbm9kZS1rZXk9XCJpZFwiIDpyZWY9XCJzZXRUcmVlUmVmXCI+XG4gICAgICAgIDwhLS0gZWwtdHJlZeeahOiKgueCueaooeadvyAtLT5cbiAgICAgICAgPCEtLSBlbC10cmVlJ3Mgbm9kZSB0ZW1wbGF0ZSAtLT5cbiAgICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwieyBub2RlLCBkYXRhIH1cIj5cbiAgICAgICAgICA8ZGl2IGNsYXNzPVwiY3VzdG9tLXRyZWUtbm9kZVwiPlxuICAgICAgICAgICAgPHNwYW4gY2xhc3M9XCJ0cmVlLWNvbnRlbnQtbmFtZVwiIHYtaWY9XCJkYXRhLnBpZCA+IDBcIj57eyBkYXRhLm5hbWUgfX08L3NwYW4+XG4gICAgICAgICAgICA8c3BhbiBjbGFzcz1cInRyZWUtY29udGVudC1uYW1lXCIgdi1lbHNlPnt7IGRhdGEubmFtZSB9fTwvc3Bhbj5cbiAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIDwvZWwtdHJlZT5cbiAgICAgIDx0ZW1wbGF0ZSAjdGl0bGU+XG4gICAgICAgIENvbnNpc3RlbmN5IDxlbC1idXR0b24gc2l6ZT1cInNtYWxsXCIgdHlwZT1cInByaW1hcnlcIiB2LXNob3c9XCJzaG93UGFyZW50RWRpdEJ1dHRvbltpdGVtLmlkXVwiPnRlc3QtZWRpdDwvZWwtYnV0dG9uPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIDwhLS0g6L+Z5pi+56S655qE5piv54i257qn6I+c5Y2V55qE57yW6L6R5oyJ6ZKuIC0tPlxuICAgICAgPGVsLWJ1dHRvbiBjbGFzcz1cInBhcmVudC1tZW51LWVkaXQtYnV0dG9uXCIgc2l6ZT1cInNtYWxsXCIgdi1zaG93PVwic2hvd1BhcmVudEVkaXRCdXR0b25baXRlbS5pZF1cIiA6aWNvbj1cIkVkaXRcIlxuICAgICAgICB0eXBlPVwicHJpbWFyeVwiPkVkaXQ8L2VsLWJ1dHRvbj5cbiAgICA8L2VsLWNvbGxhcHNlLWl0ZW0+XG4gIDwvZWwtY29sbGFwc2U+XG48L3RlbXBsYXRlPlxuXG48c3R5bGU+XG4uZWwtY29sbGFwc2UtaXRlbS5lbC1jb2xsYXBzZS1pdGVtLWVsZSB7XG4gIHBvc2l0aW9uOiByZWxhdGl2ZTtcbn1cblxuLnBhcmVudC1tZW51LWVkaXQtYnV0dG9uIHtcbiAgY3Vyc29yOiBwb2ludGVyO1xuICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gIHRvcDogMTJweDtcbiAgcmlnaHQ6IDcwcHg7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

good job man!
