### ISSUE TITLE
[Component] [select] el-select default-first-option uses hard-coded "value" and ignores "value-key"

### ISSUE THREAD

**Issue by plehnen** [element-plus/element-plus#14139]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.12`
- Browser / OS: `Chrome (latest)`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgdjEgPSByZWYoKVxuY29uc3QgdjIgPSByZWYoKVxuY29uc3Qgb3B0aW9uczEgPSBbeyB2YWx1ZTogJ2EnLCBsYWJlbDogJ0EnIH0sIHsgdmFsdWU6ICdiJywgbGFiZWw6ICdCJ30sIHsgdmFsdWU6ICdiMicsIGxhYmVsOiAnQjInfV07XG5jb25zdCBvcHRpb25zMiA9IFt7IG90aGVyOiAnYScsIGxhYmVsOiAnQScgfSwgeyBvdGhlcjogJ2InLCBsYWJlbDogJ0InfSwgeyBvdGhlcjogJ2IyJywgbGFiZWw6ICdCMid9XTtcblxuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8cD50eXBlIFwiYlwiIGFuZCBoaXQgRU5URVIuIFdpbGwgc2VsZWN0IFwiYlwiLiBDb3JyZWN0LjwvcD5cbiAgPGgxPnt7IHYxIH19PC9oMT5cbiAgPGVsLXNlbGVjdCB2LW1vZGVsPVwidjFcIiBmaWx0ZXJhYmxlIGRlZmF1bHQtZmlyc3Qtb3B0aW9uIHZhbHVlLWtleT1cInZhbHVlXCI+XG4gICAgPGVsLW9wdGlvblxuICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnMxXCJcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgLz5cbiAgPC9lbC1zZWxlY3Q+XG5cbiAgPHA+dHlwZSBcImJcIiBhbmQgaGl0IEVOVEVSLiBXaWxsIHNlbGVjdCBcImFcIi4gQnV0IHdoeT88L3A+XG4gIDxoMT57eyB2MiB9fTwvaDE+XG4gIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInYyXCIgZmlsdGVyYWJsZSBkZWZhdWx0LWZpcnN0LW9wdGlvbiB2YWx1ZS1rZXk9XCJvdGhlclwiPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zMlwiXG4gICAgICA6a2V5PVwiaXRlbS5vdGhlclwiXG4gICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgIDp2YWx1ZT1cIml0ZW0ub3RoZXJcIlxuICAgIC8+XG4gIDwvZWwtc2VsZWN0PlxuXG4gIDxwPk9ic2VydmF0aW9uczogT25seSBkaWZmZXJlbmNlIGJldHdlZW4gdGhvc2UgdHdvIGV4YW1wbGVzIGlzIHRoZSBwcm9wZXJ0eSBcInZhbHVlXCIgd2hpY2ggaXMgY2FsbGVkIFwib3RoZXJcIiBpbiB0aGUgc2Vjb25kIG9uZS4gSXQgc2VlbXMgdGhhdCBpbnRlcm5hbGx5IFwidmFsdWVcIiBpcyBoYXJkLWNvZGVkIGFuZCB2YWx1ZS1rZXkgaXMgaWdub3JlZC48L3A+XG5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

See the playground example.

Type "b" and hit ENTER in the first example. It works as expected.

Type "b" and hit ENTER in the second example. 

### What is Expected?

It should behave identical and "b" should be selected.

### What is actually happening?

The wrong entry is selected. Even though both examples are identical, except that the property is called "value" in the first example and "other" in the second example.

### Additional comments

The property "value-key" seems to be ignored here and a hard-coded "value" seems to be used.

**Comment by tolking** [comment]
I do not quite understand what the issues is. 

But the value-key is used when the binding value is an object

**Comment by tolking** [comment]
```
      :value="item.value"


      :value="item.other"
```

The value of the binding is a string

**Comment by plehnen** [comment]
Still not sure if we have a different understanding or talking about different things. The `options` are an array containing of objects, not strings. And `value-key` is pointing to the unique identifier property in each of those objects, like it is shown here: https://element-plus.org/en-US/component/select.html#use-value-key-attribute

**Comment by kaine0923** [comment]
> ```
>       :value="item.value"
> 
> 
>       :value="item.other"
> ```
> 
> The value of the binding is a string

I guess it is the docs example that is wrong about the `value-key`

**Comment by tolking** [comment]
> I guess it is the docs example that is wrong about the value-key

There is no problem with the demo in the document. Use the `value-key` when the value of the ElOption is bound to an object (`:value="item"`)

**Comment by plehnen** [comment]
I think this discussion about whether its an object or a string doesn't matter here. In the playground both examples are using it in the exact same way. The only difference is the name inside the value (and accordingly the prop which it's pointing to).

The first one works as it should. (And is how it is written in the docs, too.)
The second should also work identically, as I've just changed names but kept everything in sync. But it doesn't. That is the problem. The internal value is somehow hard-coded and not using the variable I am providing.
Or in other words: The variable name I am providing has effect of the fact whether it's working or not (which is not expected, nor desired).

**Comment by plehnen** [comment]
but as this PR (https://github.com/element-plus/element-plus/pull/14141) seems to have solved it already, I don't understand the need to discuss this any further at all ;)

**Comment by jkappel71** [comment]
> I think this discussion about whether its an object or a string doesn't matter here. In the playground both examples are using it in the exact same way. The only difference is the name inside the value (and accordingly the prop which it's pointing to).
> 
> The first one works as it should. (And is how it is written in the docs, too.) The second should also work identically, as I've just changed names but kept everything in sync. But it doesn't. That is the problem. The internal value is somehow hard-coded and not using the variable I am providing. Or in other words: The variable name I am providing has effect of the fact whether it's working or not (which is not expected, nor desired).

He is correct and this is still an issue with the latest version of the select component.  If your object that your passing in has 2 props label, and id.  The in the el-option you set the value to the object rather than a prop on the object and you set the value-key="id", when you search for something and press enter, the wrong thing is selected.  It's the first item in your entire list that gets selected, rather than the first item in the filtered list.

Here is an [example](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCIgZmlsdGVyYWJsZSBkZWZhdWx0LWZpcnN0LW9wdGlvbiB2YWx1ZS1rZXk9XCJpZFwiIHN0eWxlPVwid2lkdGg6IDI0MHB4XCI+XG4gICAgPGVsLW9wdGlvblxuICAgICAgdi1mb3I9XCJpdGVtIGluIGNpdGllc1wiXG4gICAgICA6a2V5PVwiaXRlbS5pZFwiXG4gICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgIDp2YWx1ZT1cIml0ZW1cIlxuICAgID5cbiAgICAgIDxzcGFuIHN0eWxlPVwiZmxvYXQ6IGxlZnRcIj57eyBpdGVtLmxhYmVsIH19PC9zcGFuPlxuICAgICAgPHNwYW5cbiAgICAgICAgc3R5bGU9XCJcbiAgICAgICAgICBmbG9hdDogcmlnaHQ7XG4gICAgICAgICAgY29sb3I6IHZhcigtLWVsLXRleHQtY29sb3Itc2Vjb25kYXJ5KTtcbiAgICAgICAgICBmb250LXNpemU6IDEzcHg7XG4gICAgICAgIFwiXG4gICAgICA+XG4gICAgICAgIHt7IGl0ZW0ubGFiZWwgfX1cbiAgICAgIDwvc3Bhbj5cbiAgICA8L2VsLW9wdGlvbj5cbiAgPC9lbC1zZWxlY3Q+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZSA9IHJlZignJylcbmNvbnN0IGNpdGllcyA9IFtcbiAge1xuICAgIGlkOiAxLFxuICAgIGxhYmVsOiAnQmVpamluZycsXG4gIH0sXG4gIHtcbiAgICBpZDogMixcbiAgICBsYWJlbDogJ1NoYW5naGFpJyxcbiAgfSxcbiAge1xuICAgIGlkOiAzLFxuICAgIGxhYmVsOiAnTmFuamluZycsXG4gIH0sXG4gIHtcbiAgICBpZDogNCxcbiAgICBsYWJlbDogJ0NoZW5nZHUnLFxuICB9LFxuICB7XG4gICAgaWQ6IDUsXG4gICAgbGFiZWw6ICdTaGVuemhlbicsXG4gIH0sXG4gIHtcbiAgICBpZDogNixcbiAgICBsYWJlbDogJ0d1YW5nemhvdScsXG4gIH0sXG5dXG48L3NjcmlwdD5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuMy4xNC9kaXN0L2luZGV4LmNzcycsICdodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0AyLjMuMTQvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuMy4xNC9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuMy4xNC9cIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6e319).
