### ISSUE TITLE
[Component] [icon] el-icon doesn't support specifying color through class.

### ISSUE THREAD

**Issue by OnlyWick** [element-plus/element-plus#15094]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.0-alpha.4`
- Element Plus Version: `2.4.3`
- Browser / OS: ` Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-icon`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cInRleHRcIj5cbiAgICA8ZWwtaWNvbiBjbGFzcz1cInJlZFwiPlxuICAgICAgPEVsZW1lbnRQbHVzIC8+XG4gICAgPC9lbC1pY29uPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZT5cbi5yZWQge1xuIGNvbG9yOiByZWQ7XG59XG48L3N0eWxlPlxuXG48c3R5bGUgc2NvcGVkPlxuLnRleHQge1xuIGNvbG9yOiBibHVlO1xufVxuPC9zdHlsZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

see playground.

### What is Expected?

Icon support specifying color through class.

### What is actually happening?

Icon doesn't support specifying color through class.

### Additional comments

_(empty)_

**Comment by OnlyWick** [comment]
Assign it to me.

**Comment by cuongle-hdwebsoft** [comment]
Did you forget to add the `scoped` attribute to `style`? Here is [the example](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWljb24gY2xhc3M9XCJyZWRcIj5cbiAgICA8RWxlbWVudFBsdXMgLz5cbiAgPC9lbC1pY29uPlxuPC90ZW1wbGF0ZT5cblxuXG48c3R5bGUgc2NvcGVkPlxuLnJlZCB7XG4gY29sb3I6IHJlZDtcbn1cbjwvc3R5bGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==).

**Comment by OnlyWick** [comment]
@cuongle-hdwebsoft sorry, my bad. But, this is not the way I use it, I use tailwindcss.

**Comment by OnlyWick** [comment]
I dont write `<style ... />` in `SFC`.

**Comment by cuongle-hdwebsoft** [comment]
If you are using `taiwindcss`, I assumed you config it correctly so:
- If you can use `!important`, you can change your class to `!text-red-700`
```
<el-icon class="!text-red-700">
    <ElementPlus />
</el-icon>
```

- Solution 2:
```
<style scoped lang="scss">
.your-icon-class {
  @apply text-red-700
}
</style>
```

**Comment by OnlyWick** [comment]
@cuongle-hdwebsoft thank you for your solutions, I don't wanna use `!important`, and `scss` is not used in my project.

**Comment by cuongle-hdwebsoft** [comment]
There are maybe some cases we need to `inherit`, [here is example](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEVsQnV0dG9uIHR5cGU9XCJ0ZXh0XCI+XG4gICAgSGVsbG8gd29ybGRcbiAgICA8ZWwtaWNvbiBjbGFzcz1cIlwiPlxuICAgICAgPEVsZW1lbnRQbHVzIC8+XG4gICAgPC9lbC1pY29uPlxuICA8L0VsQnV0dG9uPlxuPC90ZW1wbGF0ZT5cblxuXG48c3R5bGUgc2NvcGVkPlxuLnJlZCB7XG4gY29sb3I6IHJlZDtcbn1cbjwvc3R5bGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==). You don't need to set `color` for the icon, it will fallback that color from the parent. So I think that's why we need that config

**Comment by cuongle-hdwebsoft** [comment]
> @cuongle-hdwebsoft thank you for your solutions, I don't wanna use `!important`, and `scss` is not used in my project.

You can do it with your `css` too. Just try it 😄

**Comment by OnlyWick** [comment]
`inherit` is implict value, if we dont write it, it will also appear in css.

**Comment by OnlyWick** [comment]
I just want to use `class` directly in `<el-icon />`, and I think it must can work.

**Comment by chaigedash** [comment]
If you used _<el-icon>_，try to use attributes _color_ instead of css class selector. Be Like: `<el-icon color="red"></el-icon>`.

**Comment by chaigedash** [comment]
If you used _el-icon_，try to use attributes _color_ instead of css class selector. Be Like: `<el-icon color="red"></el-icon>`.

**Comment by chaigedash** [comment]
这里是小柴，您的邮件我已收到m^._.^m
