### ISSUE TITLE
[Component] [menu] menu菜单的:default-active动态设置为route.path，刷新后未在激活状态

### ISSUE THREAD

**Issue by LB-nan** [element-plus/element-plus#15563]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.14`
- Element Plus Version: `2.3.1`
- Browser / OS: `mac`
- Build Tool: `Vite`

### Related Component

- `el-menu`

### Steps to reproduce

```vue
  <el-menu
    class="el-menu-vertical-demo"
    :router="true"
    :default-openeds="['1','2']"
    :default-active="route.path"
  >
    <el-sub-menu index="1">
      <template #title>
        <el-icon><Operation /></el-icon>
        <span>权限管理</span>
      </template>
      <el-menu-item index="/manage/sysDept/goDeptList"><el-icon><Operation /></el-icon>部门管理</el-menu-item>
      <el-menu-item index="/manage/sysRole/goRoleList"><el-icon><Operation /></el-icon>角色管理</el-menu-item>
      <el-menu-item index="/manage/sysMenu/goMenuList"><el-icon><Operation /></el-icon>菜单管理</el-menu-item>
      <el-menu-item index="1-4"><el-icon><Operation /></el-icon>用户管理</el-menu-item>
      <el-menu-item index="1-5"><el-icon><Operation /></el-icon>数据字典</el-menu-item>
    </el-sub-menu>
    <el-sub-menu index="2">
      <template #title>
        <el-icon><Operation /></el-icon>
        <span>日志管理</span>
      </template>
      <el-menu-item index="2-1"><el-icon><Operation /></el-icon>日志列表</el-menu-item>
      <el-menu-item index="2-2"><el-icon><Operation /></el-icon>短信记录</el-menu-item>
    </el-sub-menu>
  </el-menu>

<script lang="ts" setup>
import { ref } from "vue";
import { Operation } from "@element-plus/icons-vue";
import { useRouter } from "vue-router";
const isCollapse = ref(true);
const router = useRouter();
const route = router.currentRoute.value;
console.log('route', route.path)

</script>
```

### What is Expected?

激活菜单

### What is actually happening?

未激活

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
Related #15229

**Comment by chenxch** [comment]
@LB-nan Is it convenient to provide a mini repo?

**Comment by YoungDan-hero** [comment]
> @LB-nan Is it convenient to provide a mini repo?

I think I understand where the problem lies. Starting from `vue-router` 4.x, `router.currentRoute` returns a `Ref` object, which is part of Vue 3.x's reactive system. The `Ref` object has a `value` property that contains the actual route information, including `path`, `name`, `params`, `query`, etc.

When you print `router.currentRoute` in the console, you're actually looking at this `Ref` object, which includes the `value` property. However, when you try to access `router.currentRoute.value` directly, you may encounter a problem due to the asynchronous nature of `vue-router`. By the time you try to access `router.currentRoute.value`, the route may not have fully resolved yet, so the `path` and other values inside `value` could be empty.

One solution is to access `router.currentRoute.value` inside the `onReady` hook of `vue-router`, which ensures that the route has fully resolved:

```javascript
router.isReady().then(() => {
  console.log(router.currentRoute.value);
});
```

Alternatively, you can use the `watch` feature to observe changes to `router.currentRoute`:

```javascript
import { watch } from 'vue';

watch(
  () => router.currentRoute,
  (val) => {
    console.log(val.value);
  },
  {
    immediate: true,
    deep: true,
  }
);
```

This way, you can get the latest route information whenever `router.currentRoute` changes.
