### ISSUE TITLE
[Bug Report] lockscreen not remove when dialog is destroyed

### ISSUE THREAD

**Issue by 604587986** [element-plus/element-plus#1637]
### Element Plus version
1.0.2-beta.33

### OS/Browsers version
windows

### Vue version
3.0.7

### Reproduction Link
https://codepen.io/604587986/pen/ZEBPxzm

### Steps to reproduce
click ‘show’
click 'hide'
scroll will invalid

### What is Expected?
body can scroll

### What is actually happening?
body can not  scroll

**Comment by JeremyWuuuuu** [comment]
First of all, I do not think this is a good practice on how to use `ElDialog` since the component needs to be animated, we cannot use `v-if` to control its visibility.
But I think that is something we need to handle when the component unmounted from the DOM, we need to remove all the side effects added by us.
I will fix it in the coming release.

**Comment by 604587986** [comment]
yes, this is not a good practice, Just to quickly clear the state in some component。

**Comment by inottn** [comment]
@JeremyWuuuuu  Maybe we can return hide method from useLockScreen and call it when the component unmounted.

**Comment by JeremyWuuuuu** [comment]
> @JeremyWuuuuu Maybe we can return hide method from useLockScreen and call it when the component unmounted.

I added cleanup functions to whomever using this hook see #1651

**Comment by JeremyWuuuuu** [comment]
Even though it was not suggested to use `ElDialog` or components like `ElDialog` this way (because it might sabotage the animation/transition). I know that you guys were concerned about the DOM being crushed but we still have an API for lazy rendering.

**IT IS** `ElementPlus`'s responsibility to prevent things like this from happening, so if you do think we have problems like this somewhere else, please let me or the team know.

Also PR is welcomed(for any issue) XD.
