### ISSUE TITLE
[Component] [table, table-column] el-table合并hover高亮问题

### ISSUE THREAD

**Issue by GetemJay** [element-plus/element-plus#16570]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.7.0`
- Browser / OS: `Chrome 124.0.6367.62 Macos`
- Build Tool: `Vite`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuY29uc3QgdGFibGVEYXRhID0gcmVmKFtcbiAgICB7XG4gICAgICAgIFwiY29kZVwiOiBcIlkxX1gwXCIsXG4gICAgICAgIFwibmFtZVwiOiBcIlkxXCIsXG4gICAgICAgIFwic3RhdGVcIjogXCLlvIDmnLpcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcImNvZGVcIjogXCJZMV9YMFwiLFxuICAgICAgICBcIm5hbWVcIjogXCJZMVwiLFxuICAgICAgICBcInN0YXRlXCI6IFwi6L+Q6KGMXCJcbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJjb2RlXCI6IFwiWTFfWDFcIixcbiAgICAgICAgXCJuYW1lXCI6IFwiWTFfeDAxXCIsXG4gICAgICAgIFwic3RhdGVcIjogXCLlvIDmnLpcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcImNvZGVcIjogXCJZMV9YMVwiLFxuICAgICAgICBcIm5hbWVcIjogXCJZMV94MDFcIixcbiAgICAgICAgXCJzdGF0ZVwiOiBcIui/kOihjFwiXG4gICAgfSxcbiAgICB7XG4gICAgICAgIFwiY29kZVwiOiBcIlkxX1gyXCIsXG4gICAgICAgIFwibmFtZVwiOiBcIlkxX3gwMlwiLFxuICAgICAgICBcInN0YXRlXCI6IFwi5byA5py6XCJcbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJjb2RlXCI6IFwiWTFfWDJcIixcbiAgICAgICAgXCJuYW1lXCI6IFwiWTFfeDAyXCIsXG4gICAgICAgIFwic3RhdGVcIjogXCLov5DooYxcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcImNvZGVcIjogXCJZMV9YM1wiLFxuICAgICAgICBcIm5hbWVcIjogXCJZMV94MDNcIixcbiAgICAgICAgXCJzdGF0ZVwiOiBcIuW8gOaculwiXG4gICAgfSxcbiAgICB7XG4gICAgICAgIFwiY29kZVwiOiBcIlkxX1gzXCIsXG4gICAgICAgIFwibmFtZVwiOiBcIlkxX3gwM1wiLFxuICAgICAgICBcInN0YXRlXCI6IFwi6L+Q6KGMXCJcbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJjb2RlXCI6IFwiWTJfWDBcIixcbiAgICAgICAgXCJuYW1lXCI6IFwiWTJcIixcbiAgICAgICAgXCJzdGF0ZVwiOiBcIuW8gOaculwiXG4gICAgfSxcbiAgICB7XG4gICAgICAgIFwiY29kZVwiOiBcIlkyX1gwXCIsXG4gICAgICAgIFwibmFtZVwiOiBcIlkyXCIsXG4gICAgICAgIFwic3RhdGVcIjogXCLov5DooYxcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcImNvZGVcIjogXCJZMl9YMVwiLFxuICAgICAgICBcIm5hbWVcIjogXCJZMl94MDFcIixcbiAgICAgICAgXCJzdGF0ZVwiOiBcIuW8gOaculwiXG4gICAgfSxcbiAgICB7XG4gICAgICAgIFwiY29kZVwiOiBcIlkyX1gxXCIsXG4gICAgICAgIFwibmFtZVwiOiBcIlkyX3gwMVwiLFxuICAgICAgICBcInN0YXRlXCI6IFwi6L+Q6KGMXCJcbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJjb2RlXCI6IFwiWTJfWDJcIixcbiAgICAgICAgXCJuYW1lXCI6IFwiWTJfeDA0XCIsXG4gICAgICAgIFwic3RhdGVcIjogXCLlvIDmnLpcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcImNvZGVcIjogXCJZMl9YMlwiLFxuICAgICAgICBcIm5hbWVcIjogXCJZMl94MDRcIixcbiAgICAgICAgXCJzdGF0ZVwiOiBcIui/kOihjFwiXG4gICAgfSxcbiAgICB7XG4gICAgICAgIFwiY29kZVwiOiBcIlkyX1gzXCIsXG4gICAgICAgIFwibmFtZVwiOiBcIlkyXzA1XCIsXG4gICAgICAgIFwic3RhdGVcIjogXCLlvIDmnLpcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcImNvZGVcIjogXCJZMl9YM1wiLFxuICAgICAgICBcIm5hbWVcIjogXCJZMl8wNVwiLFxuICAgICAgICBcInN0YXRlXCI6IFwi6L+Q6KGMXCJcbiAgICB9XG5dKVxuZnVuY3Rpb24gb2JqZWN0U3Bhbk1ldGhvZCAoeyByb3dJbmRleCwgY29sdW1uSW5kZXggfSkge1xuICBpZiAoY29sdW1uSW5kZXggPT09IDApIHtcbiAgICBpZiAocm93SW5kZXggJSA4ID09PSAwKSB7XG4gICAgICByZXR1cm4ge1xuICAgICAgICByb3dzcGFuOiA4LFxuICAgICAgICBjb2xzcGFuOiAxLFxuICAgICAgfVxuICAgIH0gZWxzZSB7XG4gICAgICByZXR1cm4ge1xuICAgICAgICByb3dzcGFuOiAwLFxuICAgICAgICBjb2xzcGFuOiAwLFxuICAgICAgfVxuICAgIH1cbiAgfVxuICBpZiAoY29sdW1uSW5kZXggPT09IDEpIHtcbiAgICBpZiAocm93SW5kZXggJSAyID09PSAwKSB7XG4gICAgICByZXR1cm4ge1xuICAgICAgICByb3dzcGFuOiAyLFxuICAgICAgICBjb2xzcGFuOiAxLFxuICAgICAgfVxuICAgIH0gZWxzZSB7XG4gICAgICByZXR1cm4ge1xuICAgICAgICByb3dzcGFuOiAwLFxuICAgICAgICBjb2xzcGFuOiAwLFxuICAgICAgfVxuICAgIH1cbiAgfVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXRhYmxlXG4gICAgYm9yZGVyXG4gICAgOmRhdGE9XCJ0YWJsZURhdGFcIlxuICAgIDpzcGFuLW1ldGhvZD1cIm9iamVjdFNwYW5NZXRob2RcIlxuICA+XG4gICAgPGVsLXRhYmxlLWNvbHVtbj5cbiAgICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJ7IHJvdyB9XCI+XG4gICAgICAgICAge3sgcm93LmNvZGUuc3BsaXQoJ18nKVswXSB9fVxuICAgICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cInN0YXRlXCIgbGFiZWw9XCJTdGF0ZVwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIlZhbHVlXCI+XG4gICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwieyByb3cgfVwiPlxuICAgICAgICAgIDxlbC1pbnB1dCAvPlxuICAgICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICA8L2VsLXRhYmxlPlxuPC90ZW1wbGF0ZT5cbiIsInNyYy9QbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctMTY0NzQtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiXG4gIH1cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwic3JjL2VsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vcHJldmlldy0xNjQ3NC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcycsICdodHRwczovL3ByZXZpZXctMTY0NzQtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbChzdHlsZXMpXG59IiwiX28iOnsic2hvd0hpZGRlbiI6dHJ1ZSwic3R5bGVTb3VyY2UiOiJodHRwczovL3ByZXZpZXctMTY0NzQtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MifX0=)

### Steps to reproduce

hover ”Y1“下面的”Y1_x01“下面的“运行“ 高亮错位

### What is Expected?

正确高亮

### What is actually happening?

高亮错行

### Additional comments

_(empty)_

![image](https://github.com/element-plus/element-plus/assets/26429903/bd5ebaf6-cc5c-45ce-b031-305e3daa4916)

**Comment by btea** [comment]
Thanks for the feedback, it should be fixed in #16517. [example](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuY29uc3QgdGFibGVEYXRhID0gcmVmKFtcbiAgICB7XG4gICAgICAgIFwiY29kZVwiOiBcIlkxX1gwXCIsXG4gICAgICAgIFwibmFtZVwiOiBcIlkxXCIsXG4gICAgICAgIFwic3RhdGVcIjogXCLlvIDmnLpcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcImNvZGVcIjogXCJZMV9YMFwiLFxuICAgICAgICBcIm5hbWVcIjogXCJZMVwiLFxuICAgICAgICBcInN0YXRlXCI6IFwi6L+Q6KGMXCJcbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJjb2RlXCI6IFwiWTFfWDFcIixcbiAgICAgICAgXCJuYW1lXCI6IFwiWTFfeDAxXCIsXG4gICAgICAgIFwic3RhdGVcIjogXCLlvIDmnLpcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcImNvZGVcIjogXCJZMV9YMVwiLFxuICAgICAgICBcIm5hbWVcIjogXCJZMV94MDFcIixcbiAgICAgICAgXCJzdGF0ZVwiOiBcIui/kOihjFwiXG4gICAgfSxcbiAgICB7XG4gICAgICAgIFwiY29kZVwiOiBcIlkxX1gyXCIsXG4gICAgICAgIFwibmFtZVwiOiBcIlkxX3gwMlwiLFxuICAgICAgICBcInN0YXRlXCI6IFwi5byA5py6XCJcbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJjb2RlXCI6IFwiWTFfWDJcIixcbiAgICAgICAgXCJuYW1lXCI6IFwiWTFfeDAyXCIsXG4gICAgICAgIFwic3RhdGVcIjogXCLov5DooYxcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcImNvZGVcIjogXCJZMV9YM1wiLFxuICAgICAgICBcIm5hbWVcIjogXCJZMV94MDNcIixcbiAgICAgICAgXCJzdGF0ZVwiOiBcIuW8gOaculwiXG4gICAgfSxcbiAgICB7XG4gICAgICAgIFwiY29kZVwiOiBcIlkxX1gzXCIsXG4gICAgICAgIFwibmFtZVwiOiBcIlkxX3gwM1wiLFxuICAgICAgICBcInN0YXRlXCI6IFwi6L+Q6KGMXCJcbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJjb2RlXCI6IFwiWTJfWDBcIixcbiAgICAgICAgXCJuYW1lXCI6IFwiWTJcIixcbiAgICAgICAgXCJzdGF0ZVwiOiBcIuW8gOaculwiXG4gICAgfSxcbiAgICB7XG4gICAgICAgIFwiY29kZVwiOiBcIlkyX1gwXCIsXG4gICAgICAgIFwibmFtZVwiOiBcIlkyXCIsXG4gICAgICAgIFwic3RhdGVcIjogXCLov5DooYxcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcImNvZGVcIjogXCJZMl9YMVwiLFxuICAgICAgICBcIm5hbWVcIjogXCJZMl94MDFcIixcbiAgICAgICAgXCJzdGF0ZVwiOiBcIuW8gOaculwiXG4gICAgfSxcbiAgICB7XG4gICAgICAgIFwiY29kZVwiOiBcIlkyX1gxXCIsXG4gICAgICAgIFwibmFtZVwiOiBcIlkyX3gwMVwiLFxuICAgICAgICBcInN0YXRlXCI6IFwi6L+Q6KGMXCJcbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJjb2RlXCI6IFwiWTJfWDJcIixcbiAgICAgICAgXCJuYW1lXCI6IFwiWTJfeDA0XCIsXG4gICAgICAgIFwic3RhdGVcIjogXCLlvIDmnLpcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcImNvZGVcIjogXCJZMl9YMlwiLFxuICAgICAgICBcIm5hbWVcIjogXCJZMl94MDRcIixcbiAgICAgICAgXCJzdGF0ZVwiOiBcIui/kOihjFwiXG4gICAgfSxcbiAgICB7XG4gICAgICAgIFwiY29kZVwiOiBcIlkyX1gzXCIsXG4gICAgICAgIFwibmFtZVwiOiBcIlkyXzA1XCIsXG4gICAgICAgIFwic3RhdGVcIjogXCLlvIDmnLpcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcImNvZGVcIjogXCJZMl9YM1wiLFxuICAgICAgICBcIm5hbWVcIjogXCJZMl8wNVwiLFxuICAgICAgICBcInN0YXRlXCI6IFwi6L+Q6KGMXCJcbiAgICB9XG5dKVxuZnVuY3Rpb24gb2JqZWN0U3Bhbk1ldGhvZCAoeyByb3dJbmRleCwgY29sdW1uSW5kZXggfSkge1xuICBpZiAoY29sdW1uSW5kZXggPT09IDApIHtcbiAgICBpZiAocm93SW5kZXggJSA4ID09PSAwKSB7XG4gICAgICByZXR1cm4ge1xuICAgICAgICByb3dzcGFuOiA4LFxuICAgICAgICBjb2xzcGFuOiAxLFxuICAgICAgfVxuICAgIH0gZWxzZSB7XG4gICAgICByZXR1cm4ge1xuICAgICAgICByb3dzcGFuOiAwLFxuICAgICAgICBjb2xzcGFuOiAwLFxuICAgICAgfVxuICAgIH1cbiAgfVxuICBpZiAoY29sdW1uSW5kZXggPT09IDEpIHtcbiAgICBpZiAocm93SW5kZXggJSAyID09PSAwKSB7XG4gICAgICByZXR1cm4ge1xuICAgICAgICByb3dzcGFuOiAyLFxuICAgICAgICBjb2xzcGFuOiAxLFxuICAgICAgfVxuICAgIH0gZWxzZSB7XG4gICAgICByZXR1cm4ge1xuICAgICAgICByb3dzcGFuOiAwLFxuICAgICAgICBjb2xzcGFuOiAwLFxuICAgICAgfVxuICAgIH1cbiAgfVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXRhYmxlXG4gICAgYm9yZGVyXG4gICAgOmRhdGE9XCJ0YWJsZURhdGFcIlxuICAgIDpzcGFuLW1ldGhvZD1cIm9iamVjdFNwYW5NZXRob2RcIlxuICA+XG4gICAgPGVsLXRhYmxlLWNvbHVtbj5cbiAgICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJ7IHJvdyB9XCI+XG4gICAgICAgICAge3sgcm93LmNvZGUuc3BsaXQoJ18nKVswXSB9fVxuICAgICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cInN0YXRlXCIgbGFiZWw9XCJTdGF0ZVwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIlZhbHVlXCI+XG4gICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwieyByb3cgfVwiPlxuICAgICAgICAgIDxlbC1pbnB1dCAvPlxuICAgICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICA8L2VsLXRhYmxlPlxuPC90ZW1wbGF0ZT5cbiIsInNyYy9QbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctMTY1MTctZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiXG4gIH1cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwic3JjL2VsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vcHJldmlldy0xNjUxNy1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcycsICdodHRwczovL3ByZXZpZXctMTY1MTctZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbChzdHlsZXMpXG59IiwiX28iOnsic2hvd0hpZGRlbiI6dHJ1ZSwic3R5bGVTb3VyY2UiOiJodHRwczovL3ByZXZpZXctMTY1MTctZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MifX0=)
