### ISSUE TITLE
[Bug Report] When a component has more than one "Popover", embedded HTML for all pop-ups is added to the DOM, not to the DOM when called

### ISSUE THREAD

**Issue by topaz-h** [element-plus/element-plus#1687]
### Element Plus version
1.0.2-beta.35

### OS/Browsers version
win10 Chrome

### Vue version
3.0.7

### Reproduction Link
https://jsfiddle.net/

### Steps to reproduce
# Reproduction Link is fake

- create a component
- add to many Popover
- result:
   Not only when triggered

### What is Expected?
Load only when triggered 

### What is actually happening?
When a component has more than one "Popover", embedded HTML for all pop-ups is added to the DOM, not to the DOM when called

**Comment by JeremyWuuuuu** [comment]
So from what I can get, you were asking for popups to have `lazy-load` feature, is that correct?

**Comment by JeremyWuuuuu** [comment]
So here is my opinion about this:
When using popups, you were most likely having some light-weighted operation/interaction, you do not really want to add heavy interactions (which causes the DOM structures to be extremely complicated). 
If you have that case, I would suggest you to use `ElDialog` instead of `ElTooltip`
