### ISSUE TITLE
[Bug Report] el-switch in table returns error: Uncaught (in promise) TypeError: Cannot set property 'checked' of null

### ISSUE THREAD

**Issue by rx2347** [element-plus/element-plus#1752]
### Element Plus version
1.0.2-beta.36

### OS/Browsers version
MacOS Catalina, Chrome 89.0.4389.114

### Vue version
3.0.11

### Reproduction Link
https://jsfiddle.net/aerbgtmx/3/

### Steps to reproduce
Create el-table and and add a switch in table column to change row data. Using that switch will work, but it will output an error: Uncaught (in promise) TypeError: Cannot set property 'checked' of null

### What is Expected?
Not putting out any errors as the switch works as expected (state change does happen, value gets changed as expected, no problems there)

### What is actually happening?
After toggling the switch the value gets changed, the switch element is updated correctly, but console logs an error: Uncaught (in promise) TypeError: Cannot set property 'checked' of null

Could not be fixed by handing out individual name attributes to all the switches in the table (see jsfiddle)

**Comment by yoyokun** [comment]
So do I.

**Comment by wqsmile** [comment]
me too~

**Comment by JeremyWuuuuu** [comment]
cc @justwiner

**Comment by JeremyWuuuuu** [comment]
We will look into what was causing the error, sorry for the inconvenience.

**Comment by JeremyWuuuuu** [comment]
I looked into the code, seems that every time the value gets changed, the entire table gets re-rendered.
The root cause is still under `el-table` instead of switch, we will fix that.

**Comment by rx2347** [comment]
> I looked into the code, seems that every time the value gets changed, the entire table gets re-rendered.
> The root cause is still under `el-table` instead of switch, we will fix that.

Hey Jeremy, thanks a lot. Great framework!

**Comment by JeremyWuuuuu** [comment]
Hi guys, after serious consideration of how to fix the bug, we decided we have to abandon the legacy code, I will refactor the table component in the next few days, because the way `ElementUI` in version 2.x implemented the component is no longer suitable for `Vue3` in the foundation, plus there were legacy rendering methods in `Vue` version 1.x.

We somehow need to adapt a better design to the new table. I am so sorry that we didn't do that before the first release, table seemed way more complicated than I expected. Since we are still at `beta`, we must do the hard decision for a better future of this project.
