### ISSUE TITLE
[bug report] invalid El input binding value

### ISSUE THREAD

**Issue by haliuhei** [element-plus/element-plus#1764]
### Element Plus version
1.0.2-beta.36

### OS/Browsers version
edge版本89.0.774.68

### Vue version
3.0.11

### Reproduction Link
https://codepen.io/6liu6/pen/bGgrePm

### Steps to reproduce
将输入框值改为 :value后输入框不展示改绑定值

### What is Expected?
正常绑定value

### What is actually happening?
没有显示该值

**Comment by JeremyWuuuuu** [comment]
Since we only support the way `v-model`, if you only want to implement it with one way binding, use `<el-input :modelValue="value" />`  instead. The binding is different to version 2.x, please note that.
I found the attribute for `value` is incorrect, we will fix it in the next release.
![image](https://user-images.githubusercontent.com/15975785/113678821-a7b6ec80-96f1-11eb-8303-ee871b61456f.png)

**Comment by SorrowX** [comment]
vue2中： 一个组件上的 v-model 默认会利用名为 value 的 prop 和名为 input 的事件

**Comment by haliuhei** [comment]
> vue2中： 一个组件上的 v-model 默认会利用名为 value 的 prop 和名为 input 的事件
> vue3中： 一个组件上的 v-model 默认会利用名为 modelValue 的 prop 和名为 onUpdate:modelValue 的事件
> eg
> 
> ```js
> <comp v-model="str"></comp>
> 会编译成这样
> function render(_ctx, _cache) {
>     with(_ctx) {
>         const {
>             resolveComponent: _resolveComponent,
>             createVNode: _createVNode,
>             openBlock: _openBlock,
>             createBlock: _createBlock
>         } = _Vue
> 
>         const _component_comp = _resolveComponent("comp")
> 
>         return (_openBlock(), _createBlock(_component_comp, {
>             modelValue: str,
>             "onUpdate:modelValue": $event => (str = $event)
>         }, null, 8 /* PROPS */ , ["modelValue", "onUpdate:modelValue"]))
>     }
> }
> ```
> 
> @haliuhei 所以要么使用v-model要么:modelValue, 可以先这么理解😂

谢谢了解了
