### ISSUE TITLE
[Bug Report] Bug of element plus in Vue's JSX syntax

### ISSUE THREAD

**Issue by LiucCheng** [element-plus/element-plus#1820]
### Element Plus version
1.0.2-beta.39

### OS/Browsers version
google

### Vue version
3.0.11

### Reproduction Link
https://jsfiddle.net/haf65z1v/3/

### Steps to reproduce
The # title attribute in <el-submenu index = "2" > < template # title > My workbench < / template > cannot be recognized and processed in Vue and JSX. At present, the project uses Vue's JSX syntax

### What is Expected?
Use the <el-submenu index ="2" : title ='xxx '> general title to transfer parameters

### What is actually happening?
It is not possible to use the menu related components of elememt in JSX syntax

**Comment by JeremyWuuuuu** [comment]
... Please know that JSX is just Javascript with XML it is still Javascript, you cannot use `-` between letters as variable.

Read the document: https://v3.vuejs.org/guide/render-function.html#jsx
![image](https://user-images.githubusercontent.com/15975785/114665388-8d06f800-9d2f-11eb-9b7d-3015d7d39cd3.png)
Closing since this is invalid issue
