### ISSUE TITLE
[Feature Request] el-switch input

### ISSUE THREAD

**Issue by xiaolannuoyi** [element-plus/element-plus#1841]
### Existing Component
Yes

### Component Name
el-switch

### Description
Input 标签 被隐藏了，且没有大小(`el-switch__input`)。所以input 上的事件是无法触发的。那这个input 有什么用呢？
状态的切换全靠div上的`@click.prevent="switchValue"`

删除掉input代码，及js 中的`input.value.checked = checked.value` ,也完全不影响使用。

**Comment by JeremyWuuuuu** [comment]
Because when you mix label with form items, you need the co-responding input element to make `label` work.
Check this out: https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/label
I hope this help you with your questions, also this issue zone is used for issues that you encountered, instead of asking us about the implementations. Please do not abuse it.

**Comment by xiaolannuoyi** [comment]
谢谢，我明白了。我原以为这是一个问题。非常感谢。
