### ISSUE TITLE
[Question] Form validation for table

### ISSUE THREAD

**Issue by vadimt2** [element-plus/element-plus#1851]
Hi,
I'm using this form:
[https://element-plus.org/#/en-US/component/form](https://element-plus.org/#/en-US/component/form
)

and i'm using this table with checkboxes:
[https://element-plus.org/#/en-US/component/table](https://element-plus.org/#/en-US/component/table)

When someone checked and unchecked the checkbox in the table can i show:
```
Please select at least one option
```
Below the table ?

and when someone submits the form and none checkboxes selected in the table it will show:?
```
Please select at least one option
```

I can do it by myself by writing my own code but i wanted to find out if there is such an option in element-plus?

**Comment by JeremyWuuuuu** [comment]
Are you using this: [multiple-select](https://element-plus.org/#/en-US/component/table#multiple-select)? If you do I think you can retrieve the selection data from `selection-change` event. Then when users click on the button you can check on the selection data you stored then report the error.

If you are not using it this way, I need to know your use case in order to help you using the components.

**Comment by vadimt2** [comment]
Yes this is what i do,
but then i need to make a custom css and a custom error.
Just if there was an error out of the box for the table in forms it would be great
