### ISSUE TITLE
[Bug Report] useStore() returns undefined after using ElLoading.service();

### ISSUE THREAD

**Issue by kai475** [element-plus/element-plus#1862]
### Element Plus version
1.0.2-beta.40

### OS/Browsers version
macOS Big Sur v11.2.3 / Google Chrome Version 90.0.4430.72 (Official Build) (x86_64)

### Vue version
3.0.11

### Reproduction Link
https://jsfiddle.net/kkthomas/24ghvwxb/34/

### Steps to reproduce
1. register store, and write the following sentences in a component setup;
2. const loading = ElLoading.service({ fullscreen: true });
3. const store = useStore();
4. console.log(store);

### What is Expected?
a store instance

### What is actually happening?
undefined

**Comment by kai475** [comment]
when I put useStore above ElLoading, useStore can return correctly

**Comment by JeremyWuuuuu** [comment]
Interesting issue, I will take a look at the root cause

**Comment by JeremyWuuuuu** [comment]
For fixing your issue, you need to move `loading.service` into `onMounted` hook, or in `mounted` options if you prefer using options API.

**Comment by JeremyWuuuuu** [comment]
So here is the root cause of your issue.
Based on how you using the service, when you use the `ElLoading.service` inside a `setup()` hook, 
1. `ElLoading.service` creates and renders a instance to the DOM.
2. Inside `Vue` it has a `currentInstance` local variable that was meant to preserve a stack value representing the current rendering instance, which needs to push/pop stack to preserve the order.
3. By using `ElLoading.service` this way you break the stack (without pushing stack, because push stack is sort of the job handled by renderer of Vue), by interrupting the rendering process which creates a new instance when you call that method.
4. then the stack gets popped, the current instance will be set to `null`.
5. and `useStore`'s implementation is like this:
```ts
function useStore(key) {
  return Vue.inject(key) // inject function uses `currentInstance` to get the store.
}
```
6. Since the stack got popped(you have 1 stack frame in this case), your `currentInstance` is no longer the correct instance(in this case it was null)
7. The inject function got not `currentInstance` then it reports the warning to your consonle:
See this screenshot:
![image](https://user-images.githubusercontent.com/15975785/115334799-9a5c3080-a1ce-11eb-88fc-c9a48393da26.png)

**Comment by JeremyWuuuuu** [comment]
The solution is as above:
```ts
import { onMounted } from 'vue'
// ... rest code
setup() {
  // You can still use this inside setup but only inside the `onMounted` block, this case you won't be able to break the internal stack maintained by `Vue`, this is also why `Vue` warns us about rendering `slots` inside `setup` hooks.
  onMounted() {
     ElLoading.service()
  }
}
```

**Comment by JeremyWuuuuu** [comment]
I will mark this as resolved since the solution has been provided. If you have any further questions, feel free to ping me.

**Comment by JeremyWuuuuu** [comment]
I will make sure that our document contains the warning about how to using this attribute.

**Comment by kai475** [comment]
thank you for the details.
