### ISSUE TITLE
[Bug Report] onChange does not work in datepicker via defineComponent(setup:(props,context)=>RenderFunction)

### ISSUE THREAD

**Issue by sheepzh** [element-plus/element-plus#2115]
### Element Plus version
1.0.2-beta.44

### OS/Browsers version
Ubuntu 20 / Chrome 87

### Vue version
3.0.11

### Reproduction Link
https://codepen.io/make-zero/pen/abJVMPZ

### Steps to reproduce
1. Click the link of codepen
1. Click the datepicker
2. Select date range

### What is Expected?
According to the events given by document, the selected result should be alerted.

### What is actually happening?
Nothing happens

**Comment by JeremyWuuuuu** [comment]
Don think this is a bug. Since the onChange event will only be emitted when the `modelValue` gets updated.
See this
![image](https://user-images.githubusercontent.com/15975785/120605243-6d16c980-c480-11eb-9779-1e500f9de0bd.png)

I looked up your code, you only passed `modelValue` without any updating handler which will not update the modelValue when the `onUpdate:model` emits, thus your onChange will not get triggered. Note the invocation order is `update:model` -> only when the model gets updated the `change` event can be emitted.

I hope my explanation solves your question and you can address your issue accordingly.
