### ISSUE TITLE
[feature request] The style cannot be set for the tool tip of the top-level title of the menu component

### ISSUE THREAD

**Issue by Mcler520** [element-plus/element-plus#2264]
### Element Plus version
1.0.2-beta.48

### OS/Browsers version
Chrome

### Vue version
3.0.11

### Reproduction Link
https://codepen.io/EnMcler/pen/xxqBRWj

### Steps to reproduce
Slide to the second menu, display the Tooltip, no configuration item to modify the Tooltip style

### What is Expected?
Add a custom class or style to change the style of the Tooltip

### What is actually happening?
Different styles

**Comment by kooriookami** [comment]
Yes, tooltip and popover can not use together.

**Comment by Mcler520** [comment]
> Yes, tooltip and popover can not use together.

Will the demand increase in the future?

**Comment by Liiked** [comment]
> > Yes, tooltip and popover can not use together.
> 
> Will the demand increase in the future?

There is no plan for users to customize inner tooltip component since it might influence the stability, layout and behavior of Tooltip itself. It might increase the fundamental risk on Element-Plus itself by customizing the very basic component -- tooltip. Instead, we recommand you to use third-party & standalone tooltip pacakge if you get any situation needs to modify tooltiop style itself.
