### ISSUE TITLE
[Bug Report] el-cascade visible-change event not triggered 

### ISSUE THREAD

**Issue by buaazs** [element-plus/element-plus#2323]
### Element Plus version
1.0.2-beta.52

### OS/Browsers version
win10/chrome 85

### Vue version
3.1.2

### Reproduction Link
https://codesandbox.io/s/nice-glade-rfd25?file=/src/App.vue

### Steps to reproduce
the visible-change not triggered either popup open nor hide 

### What is Expected?
visible-change triggered as expected

### What is actually happening?
the visible-change not triggered either popup open nor hide

**Comment by JeremyWuuuuu** [comment]
Was this working properly before?

**Comment by JeremyWuuuuu** [comment]
I clicked into your test link:
![image](https://user-images.githubusercontent.com/15975785/123211429-0b350700-d4f6-11eb-97b3-627ec8a63b8c.png)
I found that you are using 3.0.3 of vue which is a flawed version of vue, you should upgrade to 3.1.x in order to get the compatibility.

I left a screen recording below you can check it out:


https://user-images.githubusercontent.com/15975785/123211699-62d37280-d4f6-11eb-8a77-83ed8135f44a.mov

**Comment by JeremyWuuuuu** [comment]
I'll close this issue. Feel free to reopen if you have updates on this
