### ISSUE TITLE
Discussion about v-bind="$attrs"

### ISSUE THREAD

**Issue by Ryan2128** [element-plus/element-plus#235]
In vue3, `$attrs` includes `style` and `class`, but not in vue2. In vue3, one of its uses is pass attrs to `Fragment`, so it should include `style` and `class`. 

There is at least a styling error if use `v-bind="$attrs"` apply to a child node which has single root node.

Just like:
[First demo](https://github.com/element-plus/element-plus/pull/216#pullrequestreview-478143604)
[Second demo](https://github.com/element-plus/element-plus/pull/234#issue-476275046)

So I think it is necessary to discuss the question about `v-bind="$attrs"`.

I think this is actually a logical problem of component style.

But due to the CSS is not ready and many migrate task still need to be done, I think we should separate the `$attrs` at this stage instead of refactoring CSS.

Maybe we need open a new issue and write some temporary agreement at this stage?

cc @JeremyWuuuuu @zouhangwithsweet @zazzaz @hanx316

**Comment by JeremyWuuuuu** [comment]
@Ryan2128 @HerringtonDarkholme @zazzaz @zouhangwithsweet @bastarder @SimonaliaChen 

Hey, guys, I do think this issue is valuable due to the current issue we have been encountering with.

With the  change of `Vue` itself,  the element now inherit attributes like `style` `class` etc, to the component's root which was not the same behavior in **Vue 2.x**.

Due to this issue, once the child templates uses the syntax `v-bind="$attrs"` would inherit properties such as `style` `class` unexpectedly.

So we must have to come up with a solution for this issue like in #234, the ideal way is not preventing user to pass down properties like `class` to child component by disabling the `inheritAttrs` option, we need to prevent the children inheriting unwanted properties. We need a hook that essentially excludes attributes like `class` `style` etc out of the setup context.

Let's keep tracking on this issue.

cc @SimonaliaChen can you help with this?

**Comment by SimonaliaChen** [comment]
> @Ryan2128 @HerringtonDarkholme @zazzaz @zouhangwithsweet @bastarder @SimonaliaChen
> 
> Hey, guys, I do think this issue is valuable due to the current issue we have been encountering with.
> 
> With the change of `Vue` itself, the element now inherit attributes like `style` `class` etc, to the component's root which was not the same behavior in **Vue 2.x**.
> 
> Due to this issue, once the child templates uses the syntax `v-bind="$attrs"` would inherit properties such as `style` `class` unexpectedly.
> 
> So we must have to come up with a solution for this issue like in #234, the ideal way is not preventing user to pass down properties like `class` to child component by disabling the `inheritAttrs` option, we need to prevent the children inheriting unwanted properties. We need a hook that essentially excludes attributes like `class` `style` etc out of the setup context.
> 
> Let's keep tracking on this issue.
> 
> cc @SimonaliaChen can you help with this?

I'd love to give a try.

**Comment by JeremyWuuuuu** [comment]
The hook would be look like this:

Let's say we have a hook that takes 2 parameters of `ctx.attrs` and `keys to exclude`, the result returned by this hook should be an object which is **responsive** and also without any member with a name that's included in the `keys to exclude` collection

```ts
expect(useHook({a, b, c}, [b])).not.toContain(b)
```
