### ISSUE TITLE
[Bug Report] select-v2 V-model asynchronous binding data failure

### ISSUE THREAD

**Issue by Mcler520** [element-plus/element-plus#2368]
### Element Plus version
1.0.2-beta.53

### OS/Browsers version
chrome

### Vue version
3.1.2

### Reproduction Link
https://codepen.io/EnMcler/pen/KKmKpjG?editors=1111

### Steps to reproduce
see Link

### What is Expected?
see Link

### What is actually happening?
see Link

**Comment by JeremyWuuuuu** [comment]
I see, but one requirement here.

Even though I can tell what is the issue you are talking about here(because I am a maintainer in this project) but the others who is not familiar with this project might have a problem, so I am going to ask you on the next time please fill in the information which was needed (behavior, expected). We as contributor want to help the community as much as we can, but some informations are necessary for us to debug. 

@msidolphin had a fix patch on this, we will merge into the dev branch as a release candidate.

Very thankful!

**Comment by Mcler520** [comment]
> I see, but one requirement here.
> 
> Even though I can tell what is the issue you are talking about here(because I am a maintainer in this project) but the others who is not familiar with this project might have a problem, so I am going to ask you on the next time please fill in the information which was needed (behavior, expected). We as contributor want to help the community as much as we can, but some informations are necessary for us to debug.
> 
> @msidolphin had a fix patch on this, we will merge into the dev branch as a release candidate.
> 
> Very thankful!

ok

**Comment by JeremyWuuuuu** [comment]
Appreciated
