### ISSUE TITLE
[Bug Report] el-input__inner of Select contains label instead of value

### ISSUE THREAD

**Issue by Lorti** [element-plus/element-plus#2488]
### Element Plus version
1.0.2-beta.55

### OS/Browsers version
macOS 11.4, Chrome 91.0.4472.114

### Vue version
3.1.4

### Reproduction Link
https://codepen.io/Lorti/pen/ZEKOwed

### Steps to reproduce
1. Select an option from the Select component.
2. `value` and `htmlInputValue` properties do not match. `value` contains the value of the option, whereas `htmlInputValue` contains the label of the option.

### What is Expected?
The value of `el-input__inner` is set to the option's value.

This way we can simply submit the HTML form with the `submit()` method.

### What is actually happening?
The value of `el-input__inner` is set to the option's label.

Therefore people need a workaround when submitting their forms, like manually creating a FormData object from their Vue.js data properties.

![_Bug_Report__el-input__inner_of_Select_contains_label_instead_of_value](https://user-images.githubusercontent.com/2143782/125074860-25f2a880-e0be-11eb-8536-48504fc6e1e3.jpg)

**Comment by YangYmimi** [comment]
@Lorti This is not a bug. The prop value used to yourself logic ( binding v-model ). The prop label used to display ( What the user see ). If you want to use form, please try the component: [el-form ](https://element-plus.gitee.io/#/en-US/component/form)

**Comment by Lorti** [comment]
@YangYmimi thank you for your answer, but I don't think this is the intended behavior:

* As far as I understand the `<el-input>` inside of `<el-select>` is supposed to be a replacement for the native `<select>` element.
* When I use `<el-select name="someName" v-model="value">` in Vue.js Element Plus creates `<input class="el-input__inner" name="someName" type="text">` in the DOM.
* The input should behave the same as a native `<select>`, which uses the option value as its own value:

```
<select name="pets">
    <option value="dog">Dog</option>
    <option value="cat">Cat</option>
</select>
<!-- The value of 'pets' is 'dog'. -->
```

**Comment by YangYmimi** [comment]
> @YangYmimi thank you for your answer, but I don't think this is the intended behavior:
> 
> * As far as I understand the `<el-input>` inside of `<el-select>` is supposed to be a replacement for the native `<select>` element.
> * When I use `<el-select name="someName" v-model="value">` in Vue.js Element Plus creates `<input class="el-input__inner" name="someName" type="text">` in the DOM.
> * The input should behave the same as a native `<select>`, which uses the option value as its own value:
> 
> ```
> <select name="pets">
>     <option value="dog">Dog</option>
>     <option value="cat">Cat</option>
> </select>
> 
> ```

HaHa, I just understand your confusion.

**Comment by JeremyWuuuuu** [comment]
Since the UI is meant for displaying `label` as you can see the selector shows up the label, the underlaying value sometimes is not human readable say we have a complex value 
```js
var value = {
  hi: 'I am a value',
  ///...
}
```

But the label is quite simple say: `Select Me`.

The point is, the `el-input__inner` is actually used for **querying** meaning this it filters out the desired value or fetching from the remote server.

I am not sure if this answers your question. Let me know if you have any further questions, if you want to fetch `value` from `ElSelect` I think you should use `v-model` or `modelValue` approach. The underlaying implementation sometimes is just different than we expected.

**Comment by JeremyWuuuuu** [comment]
Let's just take https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox as an example since Microsoft had similar implementation like us. 

![image](https://user-images.githubusercontent.com/15975785/125379440-1aa3c380-e3c3-11eb-9889-d4c5840ad84a.png)

As you can see on the screenshot, the combobox is displaying the `text` instead of the `key`.

If you open this in `codepen` and open your console, try to select the input element and use

```javascript
console.log($0.value)
```

You will get `Option X` instead of `X`.

**Comment by Lorti** [comment]
Thank you, @JeremyWuuuuu, for your long and detailed answer. I do understand now, that this behavior is intentional. 

It prevents _progressive enhancement_, but that’s a trade-off we (as a community) accept in most applications that rely heavily on JavaScript. In our project we will use XMLHTTPRequest of fetch() to send the request to the server.
