### ISSUE TITLE
[Feature Request] Release/Stable Breaking Change List

### ISSUE THREAD

**Issue by ruleeeer** [element-plus/element-plus#2579]
### Description
I found that somthing in breaking change list  has changed(deleted and modify), and my company has a lot of element-ui projects,i want to dev a element-ui to element-plus tool,please tell me where to find stable/release list of changes,If I'm done developing it and find that most of the api have changed, it's very uncomfortable.

**Comment by msidolphin** [comment]
You can find breaking change in Pinned issues 
https://github.com/element-plus/element-plus/issues/162

**Comment by JeremyWuuuuu** [comment]
Actually I knew that Alimama Corp has been doing that for a while now, I dunno whether they have anything released yet, you may need to do some searches on this.

**Comment by JeremyWuuuuu** [comment]
Since this project is expecting its first stable release(meaning stabilizing the API) at the end of this year(yes we know that's kind of late, since we have lots of things to do and we only got limited number of contributors, that's the best we can do now. P.S. All contributors of this project is using their spare time to work non-profitably) 

You can find most breaking changes in #162, and we might miss some of the breaking change (if you can report them to us while developing that would be great)

TBH, I strongly suggest you to prevent using ElementPlus at this particular moment in production since we are at **beta**, we have planned lots of things to do but as I said we only have limited resources. I'd be grateful if I could have your understanding. Thank you so much ;)

**Comment by ruleeeer** [comment]
thank you very much,I found some missing changes when I updated vue2 to vue3,I’ll report them to you

**Comment by JeremyWuuuuu** [comment]
> thank you very much,I found some missing changes when I updated vue2 to vue3,I’ll report them to you

Thank you for understanding! We are looking forward to see contributions from you.

**Comment by ruleeeer** [comment]
@JeremyWuuuuu 
there is some missing breaking changes,i dont know if they are breaking changes because i dont find them in the https://github.com/element-plus/element-plus/issues/162.  ,and i cant edit https://github.com/element-plus/element-plus/issues/162. ,so report them to you here
`Loading` => `ElLoading`
`Message` => `ElMessage`
`MessageBox` => `ElMessageBox`
`Notification` => `ElNotification`
+ example
``` javascript
import {Loading} from 'element-ui' => import {ElLoading} from 'element-plus'
```
