### ISSUE TITLE
[feature request] officials are willing to add a component that is not commonly used. Why can't they provide a component that is very commonly used in tree select??? I'm a little confused...

### ISSUE THREAD

**Issue by zxiaozhou** [element-plus/element-plus#2623]
### Existing Component
No

### Component Name
tree select

### Description
官方有意愿去添加一个不常用的组件(Select-V2 虚拟列表选择器)(我认为是不常用的，谁去整个下拉列表那么大的数据量，疯了吧)，，而不去支持添加一个很常用的tree select组件了，，虽然有别人写好的(但官方直接支持不是更好吗？？？)，，，
如果因为别人写了官方就不支持，，那vue框架很多组件都有了了，，
官方也没必要开发了,直接写个链接地址，，这个组件引用这个人写的，那个组件又引用另外一个人写的。。。。真的搞不懂哎

**Comment by JeremyWuuuuu** [comment]
First of all, we never said we won't do `tree-select`, it's just not that high priority.
Secondly, you are saying things based on your conception, nothing is **impossible**, since `el-tree` is on the plan to be virtualized, `el-select-tree` is in our backlog.
Also we do not have that much of resources(contributors) to do all the things you guys asks, plus we are doing this without getting any compensation. **Your contribution is as much welcomed as the everyone in the community**

I'd like to repeat here:

**WE ARE ACCEPTING CONTRIBUTIONS FROM OUTSIDE THE TEAM, ElementPlus wouldn't become a great project without our amazing community, thank you!（我们欢迎来自社区的贡献）**
