### ISSUE TITLE
[Feature Request] Why use css3 var?

### ISSUE THREAD

**Issue by damienlau** [element-plus/element-plus#2726]
### Existing Component
是

### Component Name
Tabs

### Description
Which idiot used css3 var instead of common/var.less?

some components use public scss variables to clearly have better custom extensibility

**Comment by YunYouJun** [comment]
Users can modify the theme variables directly instead of compiling sass by css3 var.
This is effective for switching theme colors and adding light and dark modes in the future.

We're not going to abandon the variables of scss.
The necessary public sass variables will still be kept, it's just that the beta is in rapid iterative development and we haven't done enough to make it compatible.

**Comment by damienlau** [comment]
> Users can modify the theme variables directly instead of compiling sass by css3 var.
> This is effective for switching theme colors and adding light and dark modes in the future.
> 
> We're not going to abandon the variables of scss.
> The necessary public sass variables will still be kept, it's just that the beta is in rapid iterative development and we haven't done enough to make it compatible.

I knew it was better to use CSS3 VAR, but I drastically modified the entire project during the iteration, causing irreversible damage to the code project.

**Comment by YunYouJun** [comment]
We're sorry to hear this, we'll complete the compatibility and migration between scss and css var as soon as possible.

**Comment by JeremyWuuuuu** [comment]
Our contributors worked the a** off to implement new features to you guys for getting better experience, this is still a **beta** phase project, any change should be considered acceptable since we didn't stabilize all APIs, everything is planned for making this project thrive and making it better for using. Indeed we haven't done right with the whole branch management on this feature, and we are sorry about that, once the feature is fully delivered, it would be much better for both users and developers to implement their features. Thank you for understanding :pray:
