### ISSUE TITLE
[bug report] when the HTML zoom attribute is set to 0.8, the element table header drag event will become invalid

### ISSUE THREAD

**Issue by ljw-codeking** [element-plus/element-plus#2863]
### Element Plus version
1.0.2-beta.70

### OS/Browsers version
windows

### Vue version
3.2.0-beta.7

### Reproduction Link
https://jsfiddle.net/ljwdyy/pcwyumzv/6/

### Steps to reproduce
看链接

### What is Expected?
能拖拽

### What is actually happening?
不能拖拽

**Comment by hanx316** [comment]
Currently, we couldn't properly get the correct css zoom value through javascript since it could be set on any element not only html, and nor any javascript api can do this. It is different from the page zoom level in browsers.
[The codes here](https://github.com/element-plus/element-plus/blob/e5536eb933580b94548d629d57c561cac5617a16/packages/table/src/table-header/event-helper.ts#L122), calculate the mouse pointer's pixel and the col element's pixel to see whether it can be resized or not when moving your mouse.
Element's rect pixels will be changed through zoom value but the MouseEvent not. So there are not appropriate ways to fit the css zoom yet when calculating pixels.
Using ctrl +- to set the page zoom level is fine.
