### ISSUE TITLE
[Bug Report] Icon isn't displayed.

### ISSUE THREAD

**Issue by talah221** [element-plus/element-plus#2871]
### Element Plus version
1.0.2-beta.69

### OS/Browsers version
Latest

### Vue version
3.0.0

### Reproduction Link
https://codesandbox.io/s/ecstatic-shadow-2dult?file=/src/views/Login.vue

### Steps to reproduce
https://codesandbox.io/s/ecstatic-shadow-2dult?file=/src/views/Login.vue

### What is Expected?
I don't see the wanted icons on el-input
https://codesandbox.io/s/ecstatic-shadow-2dult?file=/src/views/Login.vue

### What is actually happening?
seeing [?] icon.

**Comment by iamkun** [comment]
![image](https://user-images.githubusercontent.com/17680888/128602593-a8b30c0d-7242-49f5-bd0c-1a94d09222e9.png)

This might be a bug from codesandbox, as we could see they load the font file as `content-type: text/html` by mistake

**Comment by iamkun** [comment]
And the correct content type on our doc website

![image](https://user-images.githubusercontent.com/17680888/128602633-78302441-f3e0-4128-8bac-30a72e825d06.png)

**Comment by talah221** [comment]
it isn't. I've uploaded my project to sandbox exaclty like I did it on IDE.

> ![image](https://user-images.githubusercontent.com/17680888/128602593-a8b30c0d-7242-49f5-bd0c-1a94d09222e9.png)
> 
> This might be a bug from codesandbox, as we could see they load the font file as `content-type: text/html` by mistake

**Comment by JeremyWuuuuu** [comment]
hi @talah221 after some research with @iamkun, we found that the font is not rendered due to some reason (probably because codesandbox introduced `fonts` in a very different way, you can see @iamkun 's screenshots. And I have some conclusion with:

In your demo:
![image](https://user-images.githubusercontent.com/15975785/128603105-ea7ca34a-acb1-456a-b5bc-c90bea306206.png)

In the documentation site:
![image](https://user-images.githubusercontent.com/15975785/128603160-abc21480-436e-4bbf-a5ba-d13df918735b.png)

**Comment by talah221** [comment]
> hi @talah221 after some research with @iamkun, we found that the font is not rendered due to some reason (probably because codesandbox introduced `fonts` in a very different way, you can see @iamkun 's screenshots. And I have some conclusion with:
> 
> In your demo:
> ![image](https://user-images.githubusercontent.com/15975785/128603105-ea7ca34a-acb1-456a-b5bc-c90bea306206.png)
> 
> In the documentation site:
> ![image](https://user-images.githubusercontent.com/15975785/128603160-abc21480-436e-4bbf-a5ba-d13df918735b.png)

this is have nothing to do with codesandbox.
this is also happening when I'm running it locally.
the codesandbox is only example for my current project to show and find what I've missed setuping the icons.

**Comment by JeremyWuuuuu** [comment]
> > hi @talah221 after some research with @iamkun, we found that the font is not rendered due to some reason (probably because codesandbox introduced `fonts` in a very different way, you can see @iamkun 's screenshots. And I have some conclusion with:
> > In your demo:
> > ![image](https://user-images.githubusercontent.com/15975785/128603105-ea7ca34a-acb1-456a-b5bc-c90bea306206.png)
> > In the documentation site:
> > ![image](https://user-images.githubusercontent.com/15975785/128603160-abc21480-436e-4bbf-a5ba-d13df918735b.png)
> 
> this is have nothing to do with codesandbox.
> this is also happening when I'm running it locally.
> the codesandbox is only example for my current project to show and find what I've missed setuping the icons.

Humm, can you make a minimal repo for me to debug for finding out what was going on here?

**Comment by JeremyWuuuuu** [comment]
The icon disappears due to this:
```scss
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
  font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
}
```
What I get with this uncommented:

![image](https://user-images.githubusercontent.com/15975785/128603894-427f0f73-9ef8-4828-ae87-413a03d34086.png)

What I get with this commented:
![image](https://user-images.githubusercontent.com/15975785/128603953-a80ed917-f8ed-4af9-a320-cf6bad8746c3.png)

The reason behind this is the same as I mentioned above: which the icon uses FontIcon, so that you change the font family for all pseudo class `:before :after` will impact the font icon rendering since the font set does not contain the font.

**Comment by JeremyWuuuuu** [comment]
Let me know if you have any further questions. :)

**Comment by JeremyWuuuuu** [comment]
BTW, if you want to fix this, you need to rule out `:before :after` for  class `el-icon`

**Comment by hanx316** [comment]
I'll close this issue. If you have any other questions related to this, feel free to reopen it.

**Comment by talah221** [comment]
Great! Spent about 3 hours debugging that.
