### ISSUE TITLE
yarn storybook 报错 Object(...) is not a function

### ISSUE THREAD

**Issue by xiaofeng-bm** [element-plus/element-plus#316]
chrome: 85.0.4183.102
yarn: 1.22.5
node: v12.18.3

windows10

![Snipaste_2020-09-16_21-34-43](https://user-images.githubusercontent.com/45890549/93344903-cee8c200-f864-11ea-894f-559b2c16b952.png)

**Comment by JeremyWuuuuu** [comment]
`StoryBook` will be deprecated in near future, use `yarn website-dev[:play]` instead.

**Comment by Ghitu** [comment]
@xiaofeng-bm if you want to make it work just update .storybook/preview.js with this


`import { addDecorator } from '@storybook/html'
import { createApp } from 'vue'
// import '../src/style/element-ui@2.13.2.css'
import '../packages/theme-chalk/src/index.scss'
import ElementPlus from '../packages/element-plus'
import './demo.css'

/**
 * Wraps a story into a Vue Element
 * @param {JSX.Element} template - Story templates
 * @param {VueElement}
 */
const Wrapper = (template) => {
  return {
    data() {
      return {}
    },
    template,
  }
}

/**
 * Custom Addon for previewing ElementPlus component in Vue3
 * Due to lacking of support for Vue3, the rendering method has to be made by ourself
 * This method takes a template string as parameter returns a HTMLElement which will be inserted to the iframe root node by `@StoryBook`
 * @param {Story} content
 * @return {HTMLElement}
 */
function CustomDecorator(content, context) {
  const templateOrComponent = content()
  const app = typeof templateOrComponent === 'string'
    ? createApp(Wrapper(templateOrComponent))
    : createApp(templateOrComponent)
  app.use(ElementPlus)
  const entry = document.createElement('div')
  entry.className = 'element-plus-previewer'
  app.mount(entry)
  return entry
}

addDecorator(CustomDecorator);
`

**Comment by g3r4n** [comment]
> `StoryBook` will be deprecated in near future, use `yarn website-dev[:play]` instead.

@JeremyWuuuuu  Do you plan to replace StoryBook with something different ? 
yarn website-dev[:play] isn't working from my end.

**Comment by xiaofeng-bm** [comment]
> > `StoryBook` will be deprecated in near future, use `yarn website-dev[:play]` instead.
> 
> @JeremyWuuuuu Do you plan to replace StoryBook with something different ?
> `yarn website-dev[:play]` isn't working from my end, but `yarn website-dev:play` is.

yarn website-dev:play is erroy "'PLAY_ENV' 不是内部或外部命令，也不是可运行的程序"

**Comment by zazzaz** [comment]
@xiaofeng-bm use `npx cross-env PLAY_ENV=true yarn website-dev`

**Comment by JeremyWuuuuu** [comment]
> > > `StoryBook` will be deprecated in near future, use `yarn website-dev[:play]` instead.
> > 
> > 
> > @JeremyWuuuuu Do you plan to replace StoryBook with something different ?
> > `yarn website-dev[:play]` isn't working from my end, but `yarn website-dev:play` is.
> 
> yarn website-dev:play is erroy "'PLAY_ENV' 不是内部或外部命令，也不是可运行的程序"

For `Windows` users you need to refer to @zazzaz 's suggestion in order to get your program work
> `$ npx cross-env PLAY_ENV=true yarn website-dev`
