### ISSUE TITLE
[Bug Report] el-input-number did not trigger the focus and blur methods

### ISSUE THREAD

**Issue by xmh0706** [element-plus/element-plus#3334]
### Element Plus version
1.1.0-beta.9

### OS/Browsers version
chrome93.0.4577.63

### Vue version
3.2.11

### Reproduction Link
https://codepen.io/pen/

### Steps to reproduce

```
  <el-input-number size="mini" ref="test" v-model="num4"></el-input-number>
    this.$refs.test.focus()
```

使用focus方法无法使焦点在该组件上,看了源码是没有写focus和blur方法

### What is Expected?
加入focus和blur方法

### What is actually happening?
focus和blur无效

**Comment by xiaoxian521** [comment]
@xmh0706 you can try `this.$refs.test.input.focus`

**Comment by KawaiiZapic** [comment]
About this component there is a another bug.  
When try to interact with `el-input-number` with double touch on trackpad(double touch == click on trackpad), count will increase for twice.  
It's caused by the impl of [repeat-click](https://github.com/element-plus/element-plus/blob/dev/packages/directives/repeat-click/index.ts#L18).  
There is a delay between `mouseup` and `mousedown` event when trigger click on trackpad, about 300ms, but the trigger 
threshold of repeat-click only 100ms. So click event will repeat for serveral times.  
My resolution is just add a `setTimeout` before the `setInterval`, like this:
```js
    let interval = null
    let startTime: number
    const handler = () => binding.value && binding.value()
    const clear = () => {
      if (Date.now() - startTime < 100) {
        handler()
      }
      cleartTimeout(interval)
      clearInterval(interval)
      interval = null
    }

    on(el, 'mousedown', (e: MouseEvent) => {
      if ((e as any).button !== 0) return
      startTime = Date.now()
      once(document as any, 'mouseup', clear)
      clearInterval(interval)
      handler();
      setTimeout(() => interval = setInterval(handler, 100), 300);
    })
```
