### ISSUE TITLE
[Bug Report] FormItem does not re-validate after its rules changed

### ISSUE THREAD

**Issue by halfkai** [element-plus/element-plus#3483]
### Element Plus version
1.1.0-beta.12

### OS/Browsers version
MacOS / Chrome 93

### Vue version
3.2.12

### Reproduction Link
https://codesandbox.io/s/wonderful-microservice-dfc98

### Steps to reproduce
1. click on input then click on blank space right after;
2. open codesandbox console, then click "Change Rules" Button;
3. repeat step1.

### What is Expected?
on step1: a red text "pls input" below the input box;
on step2: two output messages in console, showing that "inputRules" and "required" has already changed(required message changed to "please input");
on step3: red text changed to "please input" -------------- validate on form-item rules changes;

### What is actually happening?
on step3 validate message text doesn't change, form-item does not re-validate on rules changes

**Comment by kai475** [comment]
I don't know whether this should be [Feature Request] or not, bear with me though...

My first attempt was to make validation-text responsive, I need the text changed when page locale changed ( I have use watch and nextTick to solve the problem...) ,  Then I thought of other situations that also in need of this feature....

So here are some ideas:
1. export form-item's validate function, make them avaliable on certain form-item instead of using the whole form obj.
2. add a prop like form's validateOnRuleChange.

**Comment by sxzz** [comment]
Fixed via #5401
