### ISSUE TITLE
Dialog New Functions Discuss

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#404]
If that' all right, I hope that dialog add these functions:
1.draggable
It can drag header and move the position.
2.multilayer
It can open several dialogs, once click the bottom dialog, its index reach the top.
![image](https://user-images.githubusercontent.com/38392315/95701981-98447280-0c7d-11eb-9fea-1f636f7b22e8.png)
3.maximize
It can maximize the dialog.
![image](https://user-images.githubusercontent.com/38392315/95702281-74356100-0c7e-11eb-90ab-7fa9f2eac03d.png)
4.minimize
It can minimize the dialog.
![image](https://user-images.githubusercontent.com/38392315/95702323-97601080-0c7e-11eb-8826-5777c38f1b5d.png)
The demo url. https://www.layui.com/demo/layer.html

**Comment by JeremyWuuuuu** [comment]
Well, IMHO, `draggable` is a good feature that we could implement it in the next stage, but stacking the modals seems to be a bad feature though, modern UI libraries like `AntDesign`, `FluentUI` never implemented feature like this.

**Comment by kooriookami** [comment]
I think we can count how many people expect these feature. In fact, multiple dialogs are still common in some complex management systems.

**Comment by zhixiaotong** [comment]
> Well, IMHO, `draggable` is a good feature that we could implement it in the next stage, but stacking the modals seems to be a bad feature though, modern UI libraries like `AntDesign`, `FluentUI` never implemented feature like this.

Dialog supports full screen, but there is no button to switch full screen before the close button. I am confused about this.

**Comment by JeremyWuuuuu** [comment]
@zhixiaotong Fullscreen is a feature which have been supported programmatically, instead of providing a button that scales non-fullscreen dialog to fullscreen size, IMHO, there are merely few cases that needs this button, if user wanted to use a full size dialog, your PM/PO should be the one who makes the decision.

**Comment by JeremyWuuuuu** [comment]
> I think we can count how many people expect these feature. In fact, multiple dialogs are still common in some complex management systems.

You are right, but without knowing the sample size and its grouping stats, we cannot make the decision, we need to have some fact on that I guess.

**Comment by zhixiaotong** [comment]
@JeremyWuuuuu Indeed, there are only some cases where the full screen button needs to be displayed. But for Dialog, full-screen buttons are actually not uncommon. I personally think that it depends on the business. Since ElementUI currently does not provide a slot for the button group, we need to write additional absolutely positioned buttons, but it cannot guarantee visual consistency.

**Comment by JeremyWuuuuu** [comment]
@zhixiaotong well, maybe we can provide a field that allows user to add there own button groups as you mentioned, this could provide more flexibility to our users but it might impact title field.

**Comment by JeremyWuuuuu** [comment]
Hey guys, I am closing this issue because we want all feature requests to be tracked in discussion here is a link that you might find it helpful
https://github.com/element-plus/element-plus/discussions/905

And in order to request a new feature you can check here:

https://github.com/element-plus/element-plus/discussions/new
