### ISSUE TITLE
[Bug Report] hidden input is taking place in document

### ISSUE THREAD

**Issue by KawaiiZapic** [element-plus/element-plus#4116]
### Element Plus version
1.1.0-beta.24

### OS/Browsers version
Windows 10 / Chrome 95.0.4638.54

### Vue version
3.2.20

### Reproduction Link
https://codepen.io/kawaiizapic/pen/eYEEaaN

### Steps to reproduce
1. Create a el-input with type="hidden"
2. Look at it.

### What is Expected?
It's fully hidden, does not take any space.

### What is actually happening?
It's taking some space, leaving a big blank.

**Comment by KawaiiZapic** [comment]
If we are creating a dynamic type input, type="hidden" will help a lot.   
It's different from v-if=false.  
HTML5 Form includes the value from a hidden input but does not include a value from non-existed input.

**Comment by JeremyWuuuuu** [comment]
@KawaiiZapic Agreed, but I believe that this was caused by `el-input` wrapper.

![image](https://user-images.githubusercontent.com/15975785/139566322-4256f7d8-67cd-4d4e-bf33-6df1bd69cb33.png)

Here we have this wrapped element `div.el-input` contains nothing with `height: 0`.

Thus the `div.el-form-item__content` contains the wrapped element we mentioned above, the `line-height` property takes effect so it renders an empty DOM with height of `40px`

![image](https://user-images.githubusercontent.com/15975785/139566363-4de204a2-b93e-46e3-b693-a061e56f2571.png)

Maybe the solution is that we detect the `hidden` type to avoid the DOM from rendering, e.g.

![image](https://user-images.githubusercontent.com/15975785/139566615-26a4616a-fac4-4d10-80ee-2456471ff63b.png)

In this case we are able to get the same behavior as native `hidden` input.

Would you like to make a PR for this? 

Happy to receive contributions from you, ;) if you need any help, please feel free to ping me.

**Comment by KawaiiZapic** [comment]
#4128
