### ISSUE TITLE
add split/增加split组件

### ISSUE THREAD

**Issue by diction** [element-plus/element-plus#414]
是否可以添加split组件？

**Comment by zazzaz** [comment]
Can you please detail it?

**Comment by JeremyWuuuuu** [comment]
Are you looking for `Divider` component if I guessed it correctly, if not, please give us more detailed information about it please

**Comment by diction** [comment]
such as:
https://www.iviewui.com/components/split

**Comment by JeremyWuuuuu** [comment]
Hey guys, I am closing this issue because we want all feature requests to be tracked in discussion here is a link that you might find it helpful
https://github.com/element-plus/element-plus/discussions/905

And in order to request a new feature you can check here:

https://github.com/element-plus/element-plus/discussions/new

**Comment by xiaoxian521** [comment]
@JeremyWuuuuu I think I can add and improve this feature
