### ISSUE TITLE
[Bug Report] el-date-picker ， type="datetime"  , How do I disable input of internal time

### ISSUE THREAD

**Issue by anrui0219** [element-plus/element-plus#4145]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
google

### Vue version
3.2.20

### Reproduction Link
https://codepen.io/an-hr/pen/rNzGZXq

### Steps to reproduce
Enter the time manually,When the hour is 88, it automatically changes to 16。“editable” properties can only control external inputs, not internal inputs。How do I disable input of internal time。If not, for example, the time input 88 will automatically change to 16. What are the rules for that?
（求助国内网友：手动输入时间，当小时为88时，自动变为16。“editable”属性只能控制外部输入，而不能控制内部输入。我如何禁用内部时间的输入。如果没有，例如，时间输入88将自动更改为16。规则是什么?）
![image](https://user-images.githubusercontent.com/44487076/139634814-56759994-d3c6-4bfb-b244-a16ffd690149.png)
![image](https://user-images.githubusercontent.com/44487076/139634957-b1b9302b-8dba-4519-875e-54bba4f98053.png)

### What is Expected?
I want to disable the entry of internal times and dates。If not, what is the rule for automatically returning the time if the time is incorrectly entered manually
(求助国内网友：我想禁用内部时间和日期的输入。如果没有，手动输入错误时间自动返回时间的规则是什么)

### What is actually happening?
Our testers say this is a bug

**Comment by msidolphin** [comment]
This is javascript rule, take the remainder for 24

**Comment by JeremyWuuuuu** [comment]
I think for sure that you should argue it back because I think in the entire world everybody even young children know that we only have 24 hours per day, inputing numbers larger than `24` is meaning less, it should be consider as a **carry** in math as a result of `1 day`.

Note that this is only a time picker instead of a scheduler which is not allowed to have hour fragment to be greater than `24`. If you tester did not agree, I think you should escalate to your line manager or higher level director to discuss about it.

**Comment by JeremyWuuuuu** [comment]
This component is working as intended, if you have any problem with it, please refer to my suggestion, you need to let them know what this component is built for.

**Comment by anrui0219** [comment]
OK....Can you add a property that disables internal input

**Comment by anrui0219** [comment]
However, in the external input box, if the value exceeds 24, the date will increase accordingly, while in the internal input box, if the time exceeds 24, the date will not increase, and the internal and external rules are not uniform。Why can't you do that by adding a requirement to forbid input, even on the outside, why not on the inside
