### ISSUE TITLE
add el-input-currency/增加会计金额输入组件

### ISSUE THREAD

**Issue by diction** [element-plus/element-plus#415]
是否可以新增el-input-currency组件，或在原有el-input基础上新增功能。

**Comment by zazzaz** [comment]
Can you please detail it?

**Comment by diction** [comment]
专用于数据会计金额的input，主要功能：
①自动千分位；②设置保留固定小数位（比如不保留小数或保留两位小数）
such as：
https://ant.design/components/input-number-cn/
但是这个组件有bug，不如输入带小数的数字就不正常。

**Comment by JeremyWuuuuu** [comment]
Hey guys, I am closing this issue because we want all feature requests to be tracked in discussion here is a link that you might find it helpful
https://github.com/element-plus/element-plus/discussions/905

And in order to request a new feature you can check here:

https://github.com/element-plus/element-plus/discussions/new
