### ISSUE TITLE
[Bug Report] Input Number did not display bottom border when control position sets to right

### ISSUE THREAD

**Issue by CalsRanna** [element-plus/element-plus#4305]
### Element Plus version
1.2.0-beta.2

### OS/Browsers version
Chrome/Safari

### Vue version
3.2.21

### Reproduction Link
https://codepen.io/calsranna/pen/yLojqRE

### Steps to reproduce
null

### What is Expected?
show bottom border

### What is actually happening?
did not show bottom border

**Comment by CalsRanna** [comment]
unable to reproduce? the bottom border downside the arrow down icon. And if I use codeine from official docs which show the number input, it still has the problem.

**Comment by Alanscut** [comment]
@CalsRanna I don’t see the missing bottom border, but the missing top border is a bit like what you described
![image](https://user-images.githubusercontent.com/21104054/142791068-2acab871-5ab5-44dc-a18d-9d449f61ad1b.png)

**Comment by CalsRanna** [comment]
just like that.But somehow it fixed and i did nothing but reinstall
it.confuse.

Alan Wang ***@***.***>于2021年11月22日 周一10:14写道：

**Comment by Alanscut** [comment]
it is still exist in codepen.    https://codepen.io/littleboarx/pen/rNGVVoQ?editors=1011
![image](https://user-images.githubusercontent.com/21104054/144419727-2d55844c-6ea6-438c-8219-a1e517056369.png)
but not exist in element-plus.org
https://element-plus.org/zh-CN/component/input-number.html#%E7%B2%BE%E5%BA%A6

**Comment by hwb2017** [comment]
Refer to the codepen demo https://codepen.io/littleboarx/pen/rNGVVoQ?editors=1011, due to vertical alignment between inline elements, the input element is offset downward by about 1 px.

In the website of Element Plus, the normalize.css contains the selector rule `input { font-family: inherit }`, but the codepen environment doesn't, which makes the subtle difference magically. It seems that text realated css properties can also influence the layout of inline elements.

In a word, there are two solutions: add `font-family` property of any value, like `font-family: inherit`, or add `vertical-align: top` in the input element. The former solution looks better, you can set `font-family: inherit` in rule `.el-input__inner`, just like the rule `.el-textarea__inner` in the same file.

**Comment by chenxch** [comment]
fixed.
