### ISSUE TITLE
[bug report] El message box cannot render vnodes with global dependencies

### ISSUE THREAD

**Issue by cxj-github** [element-plus/element-plus#4474]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
macos12.0.1 chrome95.0.4638.69

### Vue version
3.2.12

### Reproduction Link
https://codesandbox.io/s/el-message-box-demo-x22yz

### Steps to reproduce
https://codesandbox.io/s/el-message-box-demo-x22yz
进入demo后，点击按钮，查看控制台

### What is Expected?
正常渲染

### What is actually happening?
1. 依赖于全局注册组件的组件不能渲染，找不到依赖的组件。
2. 依赖于全局状态(Vuex)不能渲染，不能获取全局状态。

**Comment by emojiiii** [comment]
Because vuex is implemented using provide and inject, the context that provide and inject depend on is not the same as the context of `MessageBox`, and `MessageBox` is mounted after the `microtask`, it is caused by the inability to obtain the current context

I think `MessageBox` may be difficult to fix this problem
i'm so sorry

**Comment by msidolphin** [comment]
I think this is the better solution for now, please try it. 

```js
const App = defineComponent({
  setup () {
    provide('store', store)
    return () => {
      return h(A)
    }
  },
})
const app = createApp(App);
app.mount(document.createElement("div"))
ElMessageBox({
  message: app._instance.vnode
})
```
