### ISSUE TITLE
New component TreeSelect hope

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#462]
The new component is a combination of `el-select` and `el-tree`. It can support single and multiple select. It looks like this.
Component based on version 2. https://github.com/ayiaq1/el-tree-select
![image](https://user-images.githubusercontent.com/38392315/97131316-cdbd8580-177e-11eb-84ce-44d79e4b6c41.png)
Other UI frame https://www.antdv.com/components/tree-select-cn/
![image](https://user-images.githubusercontent.com/38392315/97131306-c4ccb400-177e-11eb-9b76-bee006964bba.png)

**Comment by kooriookami** [comment]
Duplicate of #462

**Comment by JeremyWuuuuu** [comment]
@Ryan2128 Can you take a spike on this?

**Comment by Ryan2128** [comment]
YES. @JeremyWuuuuu

**Comment by JeremyWuuuuu** [comment]
Hey guys, I am closing this issue because we want all feature requests to be tracked in discussion here is a link that you might find it helpful
https://github.com/element-plus/element-plus/discussions/905

And in order to request a new feature you can check here:

https://github.com/element-plus/element-plus/discussions/new
