### ISSUE TITLE
radio-button.vue

### ISSUE THREAD

**Issue by Lliuxs** [element-plus/element-plus#511]
1.为什么不给radio-button提供change方法
2.radio-button的大部分逻辑类似 希望可以合并
3.插槽的写法和radio不一致  
       <slot></slot>
      <template v-if="!$slots.default">{{ label }}</template>
4.在使用了el-form的provider之后  为什么radio的类型不as any
return props.disabled || radioGroup_.disabled || (elForm || {} as any).disabled
5.在model的set属性中为什么需要操作instance.refs.radio && (instance.refs.radio.checked = props.modelValue === props.label)?

**Comment by JeremyWuuuuu** [comment]
I dunno what this issue is all about. 
### Question 1.
The first question I cloud answer, `radio-button` do have a change method, but it's not explicit
![image](https://user-images.githubusercontent.com/15975785/97667159-375ccd00-1aba-11eb-9464-e1f0f9b076a4.png)

### Question 2.
You are right, will do that.
### Question 3
![image](https://user-images.githubusercontent.com/15975785/97667203-52c7d800-1aba-11eb-88ac-2a4208d15201.png)
This chunk of code you saw here is logically correct, it's just not that "correct", the two parts are the exactly the same thing.

### Question 4.
This syntax is sort of incorrect, will improve it soon.

### Question 5

This is just a error tolerance measure

**Comment by JeremyWuuuuu** [comment]
Hope that this answers your question, any further question is welcomed.

**Comment by JeremyWuuuuu** [comment]
cc @zazzaz  You need check on this.

**Comment by JeremyWuuuuu** [comment]
The fix you can track it here #520

**Comment by JeremyWuuuuu** [comment]
Since there were no further response. I'm closing this issue
