### ISSUE TITLE
[Feature Request] How does this repo generate release changelogs?

### ISSUE THREAD

**Issue by davidlin88** [element-plus/element-plus#5272]
### Existing Component
No

### Component Name
None

### Description
I've been studying this project recently, I wonder how does this repo generate changelogs showed in releases, I didn't found any relevant scripts/dependencies like `lerna-changelog`.

Can someone tell me? Thank you!

**Comment by gadfly3173** [comment]
it seems generated by a customized bot @element-bot .

**Comment by iamkun** [comment]
The changelog is edited manually to get the best result.

**Comment by JeremyWuuuuu** [comment]
It is triggered automatically when we open Pull Request from `dev` to `master`, which is a hidden service that we didn't expose, and the generated report is not the perfect version since we have commit messages that didn't follow the convetion.

So we will have to check them manually.

For long term solution we will introduce a tool that checks commit input, that will allow us to do generate it completely automatically. Hope this answers your question, let me know if you have any other questions. Thank you.
