### ISSUE TITLE
Drawer not opening

### ISSUE THREAD

**Issue by wvffle** [element-plus/element-plus#549]
Drawer is not opening for me neither on https://element-plus.org/#/en-US/component/drawer nor in my own project. 

Both chromium and firefox affected.

**Comment by JeremyWuuuuu** [comment]
Sorry for the inconvenience, due to some reason the documentation has not been updated, we are working on that, there were some breaking changes we made in the new version
If you intend to open the drawer you need to use `v-model="binding"` to open, also drawer might potentially have some unexpected bugs, if you find any please tell us that we can make it better.
The current version of ElementPlus is not a official release, we do not suggest you to use it in important project.

**Comment by JeremyWuuuuu** [comment]
We will update the documentations ASAP!
