### ISSUE TITLE
[Feature Request] Please optimize first page loading time for your websites

### ISSUE THREAD

**Issue by DevDengChao** [element-plus/element-plus#6081]
### Existing Component
No

### Component Name
N/A

### Description
It task almost 30s to fully load index page https://element-plus.gitee.io/zh-CN/ when visiting the first time.
You can try clean any existing cache and refresh the page to reproduce this horrible ux.

![screenshot](https://user-images.githubusercontent.com/16363180/154192804-cf819bd6-5d9e-4033-bb19-4e94d1d5afd7.jpg)

**Comment by JeremyWuuuuu** [comment]
First of all, I think you should do a comparison between GitHub pages and Gitee pages before opening this issue.

### Github Pages
<img width="1836" alt="Github Pages" src="https://user-images.githubusercontent.com/15975785/154193556-320b411d-d739-4c01-8430-0718ff4e83ff.png">

### Gitee Pages
<img width="1836" alt="Gitee Pages" src="https://user-images.githubusercontent.com/15975785/154193701-4103fcf0-7589-4859-9b2b-576d36983b2d.png">

I think you should blame this on Gitee because of their services seems hundreds times slower than Github Pages

**Comment by JeremyWuuuuu** [comment]
Here are some suggestions you can feedback to the Gitee team:

1. Enable h2
2. Enable CDN.

**Comment by DevDengChao** [comment]
I do understand that it is the Gitee pages causes the bad experience, and Gitee should imporve thier service.

But I suggest the Element team to host the website or setup CDN themself, as new comers may leaving when they were recommended to a pool performance website. 

Will they blame Gitee pages when leaving and seeking for another UI framework?

**Comment by DevDengChao** [comment]
This is what I get when visiting https://element-plus.org/zh-CN/

![image](https://user-images.githubusercontent.com/16363180/154206441-483e999c-62e5-44fe-8bdc-6b485605fe21.png)

Seems like not better then Gitee pages.
