### ISSUE TITLE
希望table组件可以加个新增行，编辑行的扩展

### ISSUE THREAD

**Issue by Cyril5169** [element-plus/element-plus#677]
希望table组件可以加个新增行，编辑行的扩展，保存数据时可以获得哪些行是新增的，哪些行是修改的

**Comment by JeremyWuuuuu** [comment]
Could you specify the requirement? We need to estimate the effort before doing so.

**Comment by Cyril5169** [comment]
希望可以增加类似extjs那样的行编辑扩展，配置column的editor类型(input,date,select..)，编辑完成后，通过方法getNewRecords(),getUpdatedRecords(),getRemovedRecords()获得相应的改变

**Comment by JeremyWuuuuu** [comment]
Hey guys, I am closing this issue because we want all feature requests to be tracked in discussion here is a link that you might find it helpful
https://github.com/element-plus/element-plus/discussions/905

And in order to request a new feature you can check here:

https://github.com/element-plus/element-plus/discussions/new
