### ISSUE TITLE
[Bug Report] [Component] [message-box] ElMessageBox confirm button style bug

### ISSUE THREAD

**Issue by huang-yf3160** [element-plus/element-plus#6773]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.4`
- Browser / OS: `chrome 99.0.4844.82`
- Build Tool: `Vite`

### Related Component

- `el-message-box`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/message-box.html)

### Steps to reproduce

官网messagebox组件，打开message-box，按钮是鼠标悬浮样式

### What is Expected?

按钮是默认样式

### What is actually happening?

按钮是鼠标悬浮样式

### Additional comments

按钮是鼠标悬浮样式时，用户会认为当前按钮不可用

**Comment by baboon-king** [comment]
Because he is focused .

Also the style of `:hover` and ":focus" is the same
![image](https://user-images.githubusercontent.com/63645337/159674921-8402004a-744b-4f64-9079-6dfe9b2fa96e.png)

**Comment by JeremyWuuuuu** [comment]
Just for clarify, this is **NOT** a bug or deficient. It was there ever since [ElementUI](https://element.eleme.io/#/en-US/component/message-box), you can try the first demo, `disabled` and `focus` or `hover` looks slightly different. See the screenshots 👇 

![CleanShot 2022-03-23 at 20 20 08@2x](https://user-images.githubusercontent.com/15975785/159697886-388970a8-124d-4c42-80a1-959541f43575.png)

I think, this could be a chance for us to do some design enhancement to make it distinguishable between `disabled` and `focus` / `hover`

**Comment by huang-yf3160** [comment]
Should there be no focus style when opening?

**Comment by JeremyWuuuuu** [comment]
> Should there be no focus style when opening?

The feature is that we should focus on the first focusable item when opening, also traps the focus inside. See [WAI-ARIA standard for dialog/modal](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html)

**Comment by huang-yf3160** [comment]
> > Should there be no focus style when opening?
> 
> The feature is that we should focus on the first focusable item when opening, also traps the focus inside. See [WAI-ARIA standard for dialog/modal](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html)

thanks，However, the current focus/hover style and disabled style are too confusing. I hope they can be changed
