### ISSUE TITLE
[Feature Suggestion]: can ElTooltip default inserts to `DocumentBody`

### ISSUE THREAD

**Issue by Jonny-china** [element-plus/element-plus#697]
如果父元素设置了 ` overflow: hidden;` 就会不显示
![image](https://user-images.githubusercontent.com/31563977/100230182-55eea080-2f60-11eb-90f0-262be42c2e0a.png)

**Comment by JeremyWuuuuu** [comment]
Well, I think it's legit to make the API remain the same as v2 version, sure.
I will make a PR for that.

**Comment by JeremyWuuuuu** [comment]
Umm, so I went back to find out why we made this change during the migration: the reason behind making this change is that inserting tooltip to `body` causes performance issue due to the tooltip itself was positioned relatively with its parent, when we insert it to the body, `popperjs`(which is the library we use underneath this whole thing) will try to listen to the global event when the position changes (massive calculations will happen when that occurred). We have exposed an API to users named **appendToBody** to control the insertion destiny but instead of marking it `true` we decided to mark it `false` on default. So you could use this API to modify the insertion destiny on your own I think.

**Comment by Lliuxs** [comment]
我也发现这个东西没出现在body下 看了下你们的注释写的Vue did not support createVNode for Teleport
改成jsx的写法 Teleport好像是生效的 
![WX20201126-175510](https://user-images.githubusercontent.com/35122287/100335969-8d1c8a80-3010-11eb-9ab1-4b1c6ece4b0a.png)
