### ISSUE TITLE
[Feature Request] ElSelectTree & ElVirtualList

### ISSUE THREAD

**Issue by chenyuan8059** [element-plus/element-plus#725]
1、希望能够添加下拉树形组件 el-select-tree
2、希望能够添加虚拟滚动组件 el-visual-list

**Comment by zxiaozhou** [comment]
我觉得也是，，这几个都用得很平凡，频率用得高的都不提供，，那还提供啥

**Comment by JeremyWuuuuu** [comment]
Indeed, these are components that will be used in high frequency, this is on the schedule.

**Comment by JeremyWuuuuu** [comment]
Hey guys, I am closing this issue because we want all feature requests to be tracked in discussion here is a link that you might find it helpful
https://github.com/element-plus/element-plus/discussions/905

And in order to request a new feature you can check here:

https://github.com/element-plus/element-plus/discussions/new

**Comment by zazzaz** [comment]
el-visual-list #790
