### ISSUE TITLE
Select 组件设置值的问题 

### ISSUE THREAD

**Issue by VPoints** [element-plus/element-plus#739]
![image](https://user-images.githubusercontent.com/20237649/100691806-74bbbf80-33c4-11eb-8865-9306312e3221.png)
如图所示 ：
期望结果应该为 
按照正常的结果应该是 options 选择中正常匹配
然后 selectbox也正常匹配 
经过查看：
useSelect.js 中 setSelected 在 modelValue中调用 这时并未传入options watch
options.vue 中操作了父级的 cacheOptions 与options 并传入 实例对象 
但 options变更的同时并未进行 setSelected
目前可以通过 options. push的同时操作 父级的 setSelected 得到结果
我尝试着使用 watch 监听 options 或者 cacheOptions 的结果 
这和使用 react 很类似  options 并没有被监听  只有通过对象的整体变更 
例如 ： select.options = [ ...select.options ]或者其他方式
才可以监听到，再在父级中加入 watch 监听 options 变更执行 setSelect 解决问题。

希望早日修复。
同时坚决打击盗版。

**Comment by VPoints** [comment]
![image](https://user-images.githubusercontent.com/20237649/100695198-b0a65300-33cb-11eb-8e7b-1109bc7fc62e.png)
这是结果图片

上述有一个提问有个错误 ,options 解构赋值后并不需要watch
也就是只需要在 options 中进行 解构赋值即可完成该目标。

**Comment by VPoints** [comment]
期望结果
![image](https://user-images.githubusercontent.com/20237649/100695363-02e77400-33cc-11eb-970e-c0e4e9691a4f.png)
options.vue变更
![image](https://user-images.githubusercontent.com/20237649/100695408-1692da80-33cc-11eb-8d0e-f12d14e3c127.png)

**Comment by JeremyWuuuuu** [comment]
Thank you for this issue!
This might be related to the issue #687 
You interested in making a PR for this fix?

**Comment by JeremyWuuuuu** [comment]
cc @ntgraph this is definitely related to the problem that you have encountered, and we can solve that in a short time.

**Comment by JeremyWuuuuu** [comment]
So for you to understand the context I translated the comments here:
> 如图所示 ：
期望结果应该为
按照正常的结果应该是 options 选择中正常匹配
然后 selectbox也正常匹配
经过查看：
useSelect.js 中 setSelected 在 modelValue中调用 这时并未传入options watch
options.vue 中操作了父级的 cacheOptions 与options 并传入 实例对象
但 options变更的同时并未进行 setSelected
目前可以通过 options. push的同时操作 父级的 setSelected 得到结果
我尝试着使用 watch 监听 options 或者 cacheOptions 的结果
这和使用 react 很类似 options 并没有被监听 只有通过对象的整体变更
例如 ： select.options = [ ...select.options ]或者其他方式
才可以监听到，再在父级中加入 watch 监听 options 变更执行 setSelect 解决问题。

Translation:

As you can see 
The expected result should be: 
**matching the selected option and selectbox should be matched correctly**
After I inspect the code
The method named `setSelected` in `useSelect.js` was called inside the watcher callback for `modelValue`, but not for `options`. So when `options` gets updated, it did not call `setSelected` method. (The root cause of this bug)

**Comment by VPoints** [comment]
Yes, of course
But I don't know how to participate in open source projects = =。

**Comment by JeremyWuuuuu** [comment]
Simple
### Step 1
click the fork icon on the right top 

### Step 2
```shell
$ git clone the repo you just forked
```

### Step 3
1. Coding
2. Add some tests against the change you just made
3. Commit the change and push to your forked remote
4. Make a PR via fork
5. Add me as reviewer

Then it's done

**Comment by Ther-su** [comment]
@VPoints Maybe you need to run `npm run cz` to commit so that you can pass the CI

**Comment by JeremyWuuuuu** [comment]
@VPoints You need help on this? Just ask, I am glad to help

**Comment by JeremyWuuuuu** [comment]
Fixed in #808
