### ISSUE TITLE
[Feature Request] [Enhancement] [image] HTMLImageElement.loading

### ISSUE THREAD

**Issue by ryuhangyeong** [element-plus/element-plus#7841]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `image`

## Description

Currently `el-image` has lazy loading, but there is also a native loading(`loading="lazy"`) property provided by the browser. How about supporting this?

### Additional comments

https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/loading

**Comment by tolking** [comment]
Supporting native lazy loading will lose control over the image loading process, so the placeholder slots cannot be supported. But I like the idea.

**Comment by tolking** [comment]
@sxzz If the browser supports this feature, use native lazy loading, otherwise use current lazy. Or use [IntersectionObserver](https://caniuse.com/#feat=intersectionobserver) for better performance.

I wrote two plugin [vue-lazy-loading](https://github.com/tolking/vue-lazy-loading) and [vuepress-plugin-img-lazy](https://github.com/tolking/vuepress-plugin-img-lazy) before that based on this way.

**Comment by sxzz** [comment]
@tolking Good idea

**Comment by ryuhangyeong** [comment]
@tolking Are you planning to proceed with this work? I am very much looking forward to it.

**Comment by tolking** [comment]
I will try to do this.

**Comment by ryuhangyeong** [comment]
Ok~
