### ISSUE TITLE
[Feature Request] Tabs增加扩展插槽

### ISSUE THREAD

**Issue by UncleCarlos** [element-plus/element-plus#800]
参考 Ant Design

![image](https://user-images.githubusercontent.com/50797685/100970731-732efa80-3570-11eb-8578-c545595ca924.png)

期望
```html
<el-tabs>
  <el-tab-pane name="1"> xxx </el-tab-pane>
  <el-tab-pane name="2"> xxx </el-tab-pane>
  <template #extraContent>
    <i class="el-icon-delete" />
    <el-button type="primary">xxx</el-button>
    <!-- more -->
  </template>
</el-tabs>
```

比较常见的需求，暂时是用css实现了
但当tabs过多出现滚动时，与el-tabs__nav定位有些问题
希望增加插槽

**Comment by JeremyWuuuuu** [comment]
cc @bastarder

**Comment by JeremyWuuuuu** [comment]
Hey guys, I am closing this issue because we want all feature requests to be tracked in discussion here is a link that you might find it helpful
https://github.com/element-plus/element-plus/discussions/905

And in order to request a new feature you can check here:

https://github.com/element-plus/element-plus/discussions/new

**Comment by zazzaz** [comment]
I do think this is a good feature.
