### ISSUE TITLE
Select in the card will cause the display to be incomplete

### ISSUE THREAD

**Issue by lihaotian0607** [element-plus/element-plus#843]
https://jsfiddle.net/y8wd413a/9/

![image](https://user-images.githubusercontent.com/32523475/101217178-84cceb00-36b3-11eb-8021-5e2f1fa03351.png)

**Comment by SimonaliaChen** [comment]
Hi, I'm sorry to trouble you. We have changed the default value of `appendToBody` in `popper` and other components based on `popper` from `true` to `false` due to the performance issue, and I did't expect this. In this scenario, the select popper was cut off by `overflow: hidden` from parent node. You can simply add `:popper-append-to-body = true` to fix it. We will reconsider the default value issue.
