### ISSUE TITLE
[Enhancement request] mask in el-input

### ISSUE THREAD

**Issue by ntgraph** [element-plus/element-plus#854]
Hi,
I wish there is a mask option in el-input, such as like this
:mask="####"

it can be number of digit, decimal number , certain specific character or number in the input, or Regex string which in turn is providing from data or computed.

**Comment by JeremyWuuuuu** [comment]
Any demo?

**Comment by porcelainHeart** [comment]
Why not just use computed？

**Comment by JeremyWuuuuu** [comment]
Hey guys, I am closing this issue because we want all feature requests to be tracked in discussion here is a link that you might find it helpful
https://github.com/element-plus/element-plus/discussions/905

And in order to request a new feature you can check here:

https://github.com/element-plus/element-plus/discussions/new
