### ISSUE TITLE
el-tree的选择和禁用状态

### ISSUE THREAD

**Issue by Lliuxs** [element-plus/element-plus#871]
当tree只有一个children的时候 如果设置了disabled属性 这个时候点击没有任何的反应
但是点击下面的子孩子会改变checkbox的选择状态  感觉很奇怪

**Comment by Lliuxs** [comment]
https://codesandbox.io/s/cocky-tu-f35u1?file=/src/App.vue
当点击一级 1的时候下面没变化 当时选择下面的三级 1-1-2会反过来改变checkbox的选择状态
不知道是是不是数据问题

**Comment by bastarder** [comment]
i think this is not bug, in this case, you should use `check-strictly`~
if you don't have other question,  i will close this issue, thx for your feedback

**Comment by Lliuxs** [comment]
我的意思不是check-strictly
数据的选择是需要关联的  
理论上 当二级 1-1被禁止的时候 下面的应该也是不可操作的 感觉是后台返回数据问题
感谢

**Comment by JeremyWuuuuu** [comment]
> 我的意思不是check-strictly
> 数据的选择是需要关联的
> 理论上 当二级 1-1被禁止的时候 下面的应该也是不可操作的 感觉是后台返回数据问题
> 感谢

I think this is related to how you implement your business logic instead of a flaw in `el-tree` because you are the user of the component, everything is under your control. In cases like this, you might need to consider if the data design is correct. Also as @bastarder said, use `check-strictly` option for cases like this. `Disabling the parent doesn't mean the the children of it should be disabled as well, because in the end, they are also individuals right? Just like us human

**Comment by JeremyWuuuuu** [comment]
> 同时 你们自定义节点的文档 貌似重复定义了data
> return {
> data: JSON.parse(JSON.stringify(data)),
> data: JSON.parse(JSON.stringify(data))
> }

Interested in PR to fix it?

**Comment by Lliuxs** [comment]
感谢大佬  @JeremyWuuuuu  我的疑问就是你说的这样
父级disabled的时候孩子不一定是disabled 这个还是要根据具体的业务逻辑来处理
之前在使用tree组件的时候一直没使用check-strictly属性 今天联调发现选择不符合预期
一般在使用tree组件的时候都会是有关联的
我觉得这一点从官方文档没有 check-strictly 相关的demo也侧面证明这点 哈哈哈
check-strictly这个属性总感觉怪怪的 我先试下 谢谢

**Comment by bastarder** [comment]
> 我的意思不是check-strictly
> 数据的选择是需要关联的
> 理论上 当二级 1-1被禁止的时候 下面的应该也是不可操作的 感觉是后台返回数据问题
> 感谢
> 同时 你们自定义节点的文档 貌似重复定义了data
> return {
> data: JSON.parse(JSON.stringify(data)),
> data: JSON.parse(JSON.stringify(data))
> }

we will fix this, thx

**Comment by Lliuxs** [comment]
我们是否可以在这里使用jsx的方式来定义renderContent的内容？  @bastarder

**Comment by Lliuxs** [comment]
table中自定义表头的文档 貌似也有点问题 
<el-table-column
      align="right">
      <template #header #default="scope">
        <el-input
          v-model="search"
          size="mini"
          placeholder="输入关键字搜索"/>
      </template>
      <template #default="scope">  @bastarder
