### ISSUE TITLE
右键菜单需求

### ISSUE THREAD

**Issue by xiaoxian521** [element-plus/element-plus#889]
希望增加一个右键菜单组件
as  https://heynext.github.io/v-contextmenu/

**Comment by sunlifei1** [comment]
There is the same demand

**Comment by kooriookami** [comment]
Then multi-level menus and scrollbars are needed.

**Comment by xiaoxian521** [comment]
haha 你们是魔鬼吗

**Comment by JeremyWuuuuu** [comment]
Hey guys, I am closing this issue because we want all feature requests to be tracked in discussion here is a link that you might find it helpful
https://github.com/element-plus/element-plus/discussions/905

And in order to request a new feature you can check here:

https://github.com/element-plus/element-plus/discussions/new
