### ISSUE TITLE
el-table能支持columns的写法吗

### ISSUE THREAD

**Issue by Lliuxs** [element-plus/element-plus#900]
之前用andDesign 表格都是columns的写法 el-table是否可考虑支持

**Comment by Lliuxs** [comment]
ElTableColumn的type是否能增加一个单选的类型(业务有时候有这样的需求) 
现在只有多选 单选的是选择单行数据时使用色块表示 感觉使用radio是不是很更好?

**Comment by justwiner** [comment]
In order to be compatible with the usage of `element-ui/table`, `element-plus/table` will not modify the existing API for compatibility with `antdv`, this is not friendly to element-ui users.

Of course table uses `radio` for single selection, we need to discuss

**Comment by JeremyWuuuuu** [comment]
The reason behind using checkbox istead of radio button is that radio button is supposed to be displayed with groups this means you can only select single item within the group. The requirement you have posted is common but also achievable with JavaScript code, you can use the on-check emitted from el-table to do that

**Comment by JeremyWuuuuu** [comment]
I also remember that in older version table can be selected with highlighting instead of with radio button, you can also use that to achieve the feature you wanted with the first column of radio butto and bind it with tables single row selection feature. The point here is that, we kind of want to provide as simple features as we can that users can build more complex feature upon it, instead of adding too many features that the basic users won't even use at all and sacrificing the bundle sizes. Treeshaking is good but it has its limitations

**Comment by JeremyWuuuuu** [comment]
Hey guys, I am closing this issue because we want all feature requests to be tracked in discussion here is a link that you might find it helpful
https://github.com/element-plus/element-plus/discussions/905

And in order to request a new feature you can check here:

https://github.com/element-plus/element-plus/discussions/new
