### ISSUE TITLE
el-table文档错误

### ISSUE THREAD

**Issue by Lliuxs** [element-plus/element-plus#929]
![image](https://user-images.githubusercontent.com/35122287/101630660-29597f00-3a5e-11eb-977e-5180ad0b8f2f.png)

文档中 自定义列模板部分 的#trigger插槽 是否应该为reference

在el-popper中接收的插槽是 v-slots为default和trigger
但是在el-popover的trigger中 const trigger = $slots.reference ? $slots.reference() : null
这里是不是可以统一命名

**Comment by Ryan2128** [comment]
First, the slot name should be changed in this demo to make it work.

But, I think the slot name of `el-popper` should not be changed for compatibility reasons.

**Comment by JeremyWuuuuu** [comment]
When `ElPopper` was designed I didn't think about `trigger` as a way to trigger the change, so I named the slot `trigger` then there comes `trigger` for trigger option like `click.

For `ElPopover`, because we wanted to implement functionalities without breaking the previous designed API, so I didn't change the slot name for `ElPopover`
BTW, `ElPopper` was meant to be a component for internal use only, developers should not be able to know its existence

**Comment by JeremyWuuuuu** [comment]
@Lliuxs You interested in making PR for fixing this?

**Comment by Lliuxs** [comment]
其实很多时候用自带的show-overflow-tooltip可以解决问题 
但是这个属性和el-tooltip一样当内容过长时 width会占满屏幕 被人怼说太丑。。。
