### ISSUE TITLE
[Component] [form] Submit doesn't work in multiple form items

### ISSUE THREAD

**Issue by fzn0x** [element-plus/element-plus#9626]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.13`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-form`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbiAgXG4gICAgICAgIDxlbC1mb3JtIEBzdWJtaXQ9XCJzaWduSW5cIj5cbiAgICAgICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cImVtYWlsXCI+XG4gICAgICAgICAgPGVsLWlucHV0XG5cbiAgICAgICAgICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIGlucHV0IHlvdXIgZW1haWxcIlxuICAgICAgICAgICAgOmNsYXNzPVwiYG10LTE0YFwiXG4gICAgICAgICAgICBmb2N1c1xuICAgICAgICAgIC8+XG4gICAgICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgICAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwicGFzc3dvcmRcIj5cbiAgICAgICAgICA8ZWwtaW5wdXRcbiAgICAgICAgICAgIHR5cGU9XCJwYXNzd29yZFwiXG4gICAgICAgICAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBpbnB1dCB5b3VyIHBhc3N3b3JkXCJcbiAgICAgICAgICAgIDpjbGFzcz1cImBtdC02IHctZnVsbGBcIlxuICAgICAgICAgICAgc2hvdy1wYXNzd29yZFxuICAgICAgICAgIC8+XG4gICAgICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgICAgPC9lbC1mb3JtPlxuICBcbiAgICAgICAgICA8ZWwtZm9ybSBAc3VibWl0PVwic2lnbkluXCI+XG4gICAgICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJlbWFpbFwiPlxuICAgICAgICAgIDxlbC1pbnB1dFxuXG4gICAgICAgICAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBpbnB1dCB5b3VyIGVtYWlsXCJcbiAgICAgICAgICAgIDpjbGFzcz1cImBtdC0xNGBcIlxuICAgICAgICAgICAgZm9jdXNcbiAgICAgICAgICAvPlxuICAgICAgICA8L2VsLWZvcm0taXRlbT5cbiAgICAgIDwvZWwtZm9ybT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCI+XG5leHBvcnQgZGVmYXVsdCB7XG4gIG1ldGhvZHM6IHtcbiAgICBzaWduSW4oZXYpe1xuICAgICAgZXYucHJldmVudERlZmF1bHQoKVxuICAgICAgYWxlcnQoXCJHb25uYSB3b3JrXCIpXG4gICAgfVxuICB9XG59XG48L3NjcmlwdD4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

Put 2 form-item like mine inside el-form

### What is Expected?

It's works

### What is actually happening?

@submit handler not even running

### Additional comments

_(empty)_

**Comment by fzn0x** [comment]
The documentation also only provide to use @click in the example, is it intentional?

**Comment by fzn0x** [comment]
The documentation also only provide to use `@click` in the example for multiple form items, is it intentional?

**Comment by chenxch** [comment]
Please use components correctly, does `@submit` exist?

**Comment by munirapp** [comment]
Hi @fzn0x, I've seen your code on the reproduction link, and I think the reason why the `submit` event was not triggered is because you don't put any triggered element like `<button>` or `<input type="submit">` on there, also you can't trigger it by hit enter keys because you don't bind the v-model on `<el-input>` elements and causes the input can't be edited or receive an input. As noted, if you use a default component like `<el-button>` it won't trigger form submit events because the element plus rendered that component into `<button type="button"`> element. To better understand what I mean, you can access the playground code below which I modified from the code you shared

[Multiple Form with Element plus](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBlbWFpbCA9IHJlZihcIlwiKVxuY29uc3QgZW1haWwyID0gcmVmKFwiXCIpXG5jb25zdCBlbWFpbDMgPSByZWYoXCJcIilcbiAgXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+VGVzdCBNdWx0aXBsZSBGb3JtPC9oMT5cbiAgXHRcbiAgPCEtLSBGb3JtIDEgLS0+XG4gIDxoMz5Gb3JtIDE8L2gzPlxuICA8ZWwtZm9ybSBAc3VibWl0PVwic2lnbkluXCI+XG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIkVtYWlsXCI+XG4gICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cImVtYWlsXCIgcGxhY2Vob2xkZXI9XCJpbnB1dCB5b3VyIGVtYWlsXCIgY2xhc3M9XCJtdC0xNFwiIGF1dG9mb2N1cz48L2VsLWlucHV0PlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDxlbC1pbnB1dCB0eXBlPVwic3VibWl0XCI+PC9lbC1pbnB1dD5cbiAgPC9lbC1mb3JtPlxuICBcbiAgPGVsLWRpdmlkZXIgLz5cbiAgXG4gIDwhLS0gRm9ybSAyIC0tPiBcbiAgPGgzPkZvcm0gMjwvaDM+XG4gIDxlbC1mb3JtIEBzdWJtaXQ9XCJzaWduSW5cIj5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiRW1haWxcIj5cbiAgICAgIDxlbC1pbnB1dCB2LW1vZGVsPVwiZW1haWwyXCIgcGxhY2Vob2xkZXI9XCJpbnB1dCB5b3VyIGVtYWlsXCIgY2xhc3M9XCJtdC0xNFwiIGF1dG9mb2N1cz48L2VsLWlucHV0PlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDxlbC1mb3JtLWl0ZW0+XG4gICAgICA8ZWwtYWxlcnQgdHlwZT1cImVycm9yXCIgY2xhc3M9XCJtdC01IG1iLTVcIj55b3UgY2FuJ3QgdHJpZ2dlcmVkIGZvcm0gc3VibWl0IHdpdGggdGhpcyBidXR0b24gYmVsb3csIGl0IGlzIGJlY2F1c2UgdGhlIGJ1dHRvbiByZW5kZXJlZCB3aXRoIHR5cGUgYnV0dG9uIDwvZWwtYWxlcnQ+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGVsLWJ1dHRvbj5TdWJtaXQ8L2VsLWJ1dHRvbj5cbiAgPC9lbC1mb3JtPlxuICBcbiAgPGVsLWRpdmlkZXIgLz5cbiAgXG4gIDwhLS0gRm9ybSAzIC0tPlxuICA8aDM+Rm9ybSAzPC9oMz5cbiAgPGVsLWZvcm0gQHN1Ym1pdD1cInNpZ25JblwiPlxuICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJFbWFpbFwiPlxuICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJlbWFpbDNcIiBwbGFjZWhvbGRlcj1cImlucHV0IHlvdXIgZW1haWwgYW5kIGhpdCBlbnRlciBrZXlzXCIgY2xhc3M9XCJtdC0xNFwiIGF1dG9mb2N1cz48L2VsLWlucHV0PlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG4gIFxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIj5cbmV4cG9ydCBkZWZhdWx0IHtcbiAgbWV0aG9kczoge1xuICAgIHNpZ25Jbihldil7XG4gICAgICBldi5wcmV2ZW50RGVmYXVsdCgpXG4gICAgICBhbGVydChcIkdvbm5hIHdvcmtcIilcbiAgICB9XG4gIH1cbn1cbjwvc2NyaXB0PiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

[Simple Example How to Trigger submit event from HTML Form Element](https://codepen.io/munirapp/pen/XWqbzxw)

Also you can read this references:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit_event

**Comment by fzn0x** [comment]
> Hi @fzn0x, I've seen your code on the reproduction link, and I think the reason why the `submit` event was not triggered is because you don't put any triggered element like `<button>` or `<input type="submit">` on there, also you can't trigger it by hit enter keys because you don't bind the v-model on `<el-input>` elements and causes the input can't be edited or receive an input. As noted, if you use a default component like `<el-button>` it won't trigger form submit events because the element plus rendered that component into `<button type="button"`> element. To better understand what I mean, you can access the playground code below which I modified from the code you shared
> 
> [Multiple Form with Element plus](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBlbWFpbCA9IHJlZihcIlwiKVxuY29uc3QgZW1haWwyID0gcmVmKFwiXCIpXG5jb25zdCBlbWFpbDMgPSByZWYoXCJcIilcbiAgXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+VGVzdCBNdWx0aXBsZSBGb3JtPC9oMT5cbiAgXHRcbiAgPCEtLSBGb3JtIDEgLS0+XG4gIDxoMz5Gb3JtIDE8L2gzPlxuICA8ZWwtZm9ybSBAc3VibWl0PVwic2lnbkluXCI+XG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIkVtYWlsXCI+XG4gICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cImVtYWlsXCIgcGxhY2Vob2xkZXI9XCJpbnB1dCB5b3VyIGVtYWlsXCIgY2xhc3M9XCJtdC0xNFwiIGF1dG9mb2N1cz48L2VsLWlucHV0PlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDxlbC1pbnB1dCB0eXBlPVwic3VibWl0XCI+PC9lbC1pbnB1dD5cbiAgPC9lbC1mb3JtPlxuICBcbiAgPGVsLWRpdmlkZXIgLz5cbiAgXG4gIDwhLS0gRm9ybSAyIC0tPiBcbiAgPGgzPkZvcm0gMjwvaDM+XG4gIDxlbC1mb3JtIEBzdWJtaXQ9XCJzaWduSW5cIj5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiRW1haWxcIj5cbiAgICAgIDxlbC1pbnB1dCB2LW1vZGVsPVwiZW1haWwyXCIgcGxhY2Vob2xkZXI9XCJpbnB1dCB5b3VyIGVtYWlsXCIgY2xhc3M9XCJtdC0xNFwiIGF1dG9mb2N1cz48L2VsLWlucHV0PlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDxlbC1mb3JtLWl0ZW0+XG4gICAgICA8ZWwtYWxlcnQgdHlwZT1cImVycm9yXCIgY2xhc3M9XCJtdC01IG1iLTVcIj55b3UgY2FuJ3QgdHJpZ2dlcmVkIGZvcm0gc3VibWl0IHdpdGggdGhpcyBidXR0b24gYmVsb3csIGl0IGlzIGJlY2F1c2UgdGhlIGJ1dHRvbiByZW5kZXJlZCB3aXRoIHR5cGUgYnV0dG9uIDwvZWwtYWxlcnQ+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGVsLWJ1dHRvbj5TdWJtaXQ8L2VsLWJ1dHRvbj5cbiAgPC9lbC1mb3JtPlxuICBcbiAgPGVsLWRpdmlkZXIgLz5cbiAgXG4gIDwhLS0gRm9ybSAzIC0tPlxuICA8aDM+Rm9ybSAzPC9oMz5cbiAgPGVsLWZvcm0gQHN1Ym1pdD1cInNpZ25JblwiPlxuICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJFbWFpbFwiPlxuICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJlbWFpbDNcIiBwbGFjZWhvbGRlcj1cImlucHV0IHlvdXIgZW1haWwgYW5kIGhpdCBlbnRlciBrZXlzXCIgY2xhc3M9XCJtdC0xNFwiIGF1dG9mb2N1cz48L2VsLWlucHV0PlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG4gIFxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIj5cbmV4cG9ydCBkZWZhdWx0IHtcbiAgbWV0aG9kczoge1xuICAgIHNpZ25Jbihldil7XG4gICAgICBldi5wcmV2ZW50RGVmYXVsdCgpXG4gICAgICBhbGVydChcIkdvbm5hIHdvcmtcIilcbiAgICB9XG4gIH1cbn1cbjwvc2NyaXB0PiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)
> 
> [Simple Example How to Trigger submit event from HTML Form Element](https://codepen.io/munirapp/pen/XWqbzxw)
> 
> Also you can read this references: https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit_event

I miss about that, thank you for the explanation!

**Comment by fzn0x** [comment]
![image](https://user-images.githubusercontent.com/50759463/188585007-4d191401-522a-4f66-943a-c5de0de86723.png)

Solved https://element-plus.org/en-US/component/button.html#button-attributes
