### ISSUE TITLE
[Component] [input] ElInput max length rule not working when value is a number initially

### ISSUE THREAD

**Issue by plehnen** [element-plus/element-plus#9783]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.39`
- Element Plus Version: `2.2.16`
- Browser / OS: `Chrome (latest)`
- Build Tool: `Vue CLI`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlYWN0aXZlLCB2ZXJzaW9uIGFzIHZ1ZVZlcnNpb24gfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIEVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IG9iaiA9IHJlYWN0aXZlKHsgdmFsOiAxIH0pO1xuICBcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1mb3JtIDptb2RlbD1cIm9ialwiPlxuICA8ZWwtZm9ybS1pdGVtIHByb3A9XCJ2YWxcIiA6cnVsZXM9XCJ7IG1pbjogMCwgbWF4OiA1MDAsIG1lc3NhZ2U6ICdUaGUgbWF4IGFsbG93ZWQgbGVuZ3RoIG9mIDUwMCBpcyBleGNlZWRlZCcsIHRyaWdnZXI6ICdibHVyJyB9XCI+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwib2JqLnZhbFwiIC8+XG4gIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG4gIFxuICBOT1RFOiBUbyBzZWUgdGhlIHByb2JsZW0sIGp1c3QgZm9jdXMgdGhlIGlucHV0IGFuZCBjbGljayBzb21ld2hlcmUgZWxzZS4gVGhlIFwibWF4IGxlbmd0aCBlcnJvclwiIHdpbGwgYmUgc2hvd24sIGV2ZW4gdGhvdWdoIGl0J3MgbG93ZXIgdGhhbiA1MDAgYW5kIHRoZSBzdHJpbmcgaXMgc2hvcnRlciB0aGFuIDUwMC4gVGhpcyBvbmx5IGhhcHBlbnMsIHdoZW4gdGhlIGluaXRpYWwgdmFsdWUgaXMgYSBudW1iZXIuXG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

According to docs (https://github.com/yiminghe/async-validator#range) the "max" property in the rules "is performed against the length" for strings and "for number types the number must not be less than min nor greater than max".
If the value is a number initially and the input is touched, an error is always shown. Even when both conditions are not fulfilled (i.e. the value is shorter and less than "max")

### What is Expected?

The value should be treated as a string and it should be checked for "length"

### What is actually happening?

An falsy error is shown

### Additional comments

_(empty)_

**Comment by holazz** [comment]
The check fails because the default type of `rules` is string and the initial value of the input is a number. If you want to check length of number you can use `pattern`. Check out this [example](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlYWN0aXZlIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBvYmogPSByZWFjdGl2ZSh7IHZhbDogMSwgdmFsMjogMSB9KVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWZvcm0gOm1vZGVsPVwib2JqXCI+XG4gICAgPGVsLWZvcm0taXRlbVxuICAgICAgbGFiZWw9XCJDaGVjayBudW1iZXIgbGVuZ3RoXCJcbiAgICAgIHByb3A9XCJ2YWxcIlxuICAgICAgOnJ1bGVzPVwie1xuICAgICAgICBwYXR0ZXJuOiAvXlxcZHswLDUwMH0kLyxcbiAgICAgICAgdHJpZ2dlcjogJ2JsdXInLFxuICAgICAgfVwiXG4gICAgPlxuICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJvYmoudmFsXCIgLz5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgICA8ZWwtZm9ybS1pdGVtXG4gICAgICBsYWJlbD1cIkNoZWNrIG51bWJlciBzaXplXCJcbiAgICAgIHByb3A9XCJ2YWwyXCJcbiAgICAgIDpydWxlcz1cIntcbiAgICAgICAgdHlwZTogJ251bWJlcicsXG4gICAgICAgIG1pbjogMCxcbiAgICAgICAgbWF4OiA1MDAsXG4gICAgICAgIHRyaWdnZXI6ICdibHVyJyxcbiAgICAgIH1cIlxuICAgID5cbiAgICAgIDxlbC1pbnB1dCB2LW1vZGVsLm51bWJlcj1cIm9iai52YWwyXCIgLz5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgPC9lbC1mb3JtPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==).

**Comment by HeftyKoo** [comment]
I think this is a usage question. I will close this issue first, if you have any problems, welcome to open a new issue again.
